### ISSUE TITLE
Custom names using packets

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#102]

**Comment by stumper66** [comment]
Can you please add details on what this request is about?

**Comment by lokka30** [comment]
> Can you please add details on what this request is about?

Instead of actually setting the entity's CustomName, this feature will not actually name the entity on the server but clients will see a nametag of the mob through packets. This is so that the plugin does not interfere with plugins e.g. clearlag that avoid touching named entities. In addition, players that want to use a nametag on levelled entities but still have the levelled mobs nametag will be able to do so.

**Comment by lokka30** [comment]
Awaiting community response from [here](https://www.spigotmc.org/threads/changing-an-entitys-name-using-protocollib.482855/).

**Comment by lokka30** [comment]
Code done, just need to test it.

**Comment by lokka30** [comment]
The code is in and I am seeing nametags on entities, however, another issue surfaced [here](https://www.spigotmc.org/threads/changing-an-entitys-name-using-protocollib.482855/#post-4051998) which completely defeats the purpose of using packets in the first place.

**Comment by lokka30** [comment]
Packet nametags are done, just need to fix the issue in #119 as I mentioned above.
