### ISSUE TITLE
Phantoms don't level

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#108]
Most likely a similar issue to #66 and #96

**Comment by stumper66** [comment]
This is a simple fix requiring a one-liner of code.
Same fix as ghast, hoglins and magmacubes

**Comment by lokka30** [comment]
Pushed commit that may fix the issue

**Comment by lokka30** [comment]
Tested, still not working

**Comment by lokka30** [comment]
Merging this with #66 since they are the same issue.
