### ISSUE TITLE
kill checks

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#114]
Add toggleable checks which prevent the kill subcommand from killing certain levelled mobs
* Nametagged mobs
* Leashed mobs
* Tamed mobs
* Zombie villagers that are converting
* List of entity types to ignore

**Comment by stumper66** [comment]
Can you give me some ideas on how the command syntax would look like?
Would it look like this?
/lvlmobs kill allExcept (list)
(list) being any of these possible values:
- NameTagged
- Leashed
- Tamed
- ConvertingVillagers
- (Any Mob Entity Type)

**Comment by lokka30** [comment]
> Can you give me some ideas on how the command syntax would look like?
> Would it look like this?
> /lvlmobs kill allExcept (list)
> (list) being any of these possible values:
> 
> * NameTagged
> * Leashed
> * Tamed
> * ConvertingVillagers
> * (Any Mob Entity Type)

I apologise for the lack of clarity in the original post. I was meaning to add these settings to settings.yml and the kill command automatically ignores them. However, if you want them to be an optional argument then that's completely fine. I would find that more difficult to implement though, so I am more inclined to make it a global settings option.

**Comment by stumper66** [comment]
Not that I think about perhaps an interactive command much like multiverse inventories where you type in a list of items one at a time to build a group.
Then you can reference that when using the kill all except command.

**Comment by lokka30** [comment]
> Not that I think about perhaps an interactive command much like multiverse inventories where you type in a list of items one at a time to build a group.
> Then you can reference that when using the kill all except command.

Actually I was over-thinking it - I was thinking a system similar to PhantomWorlds' optional arguments thing where you do `-gs:true -t:flat` for example for 'generate structures: true, terrain: flat', however this could all be done in one argument (e.g. `[nametagged:false,leashed:true,tamed:true,convertingVillagers:false,type:ZOMBIE_VILLAGER]`

**Comment by lokka30** [comment]
Added config options, needs testing

**Comment by lokka30** [comment]
Will make kill command args a separate issue.

**Comment by lokka30** [comment]
Working
