### ISSUE TITLE
Disable mobs from being level tagged

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#127]
e.g. in entity name override, just set the mob to `disabled`.

**Comment by stumper66** [comment]
Lokka, for this request the mob will still be levelled, but no tag would be displayed?  Please clarify

**Comment by lokka30** [comment]
> Lokka, for this request the mob will still be levelled, but no tag would be displayed? Please clarify

This requester would like to be able to remove the plugin's nametags on certain entities. For this, we can allow 'entity name override' to set the nametag to 'disabled' and then the nametag methods will ignore the levelled mob if their overriden nametag is `disabled`.

**Comment by stumper66** [comment]
ok but the mob is still levelled right?

**Comment by lokka30** [comment]
Done needs testing

**Comment by lokka30** [comment]
Setting works for `creature-nametag` but does not work for `entity-name-override`.

**Comment by lokka30** [comment]
Fixed
