### ISSUE TITLE
Request: Spider jockeys and other passenger-type combinations should have the same level

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#129]
Suggested by UltimaOath

**Comment by UltimaOath** [comment]
```
apply-settings:
  match-passenger-level-on-spawn: true
```

**Comment by lokka30** [comment]
Any idea for which version we should implement this? 3.1, 3.2, 3.3, 3.4? @stumper66 @UltimaOath

**Comment by stumper66** [comment]
added to LevelledMobs v3.2.0 b512
new setting added to rules.yml under apply-settings: passenger-match-level: false

**Comment by UltimaOath** [comment]
Tested and verified core concept works; working on minor bug where stacks of more than three entities can be separated in level if separated by a non-levelled entity. Also theorizing potential ideas to improve the  nametag situation with stacked entities.

**Comment by UltimaOath** [comment]
The issue from before was fixed and the feature works as of b530
