### ISSUE TITLE
Bulletproofing

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#132]
Ensure that user config values are validated and fixed if they pose a high risk to the plugin malfunctioning.
For example, setting a min-level of `-1` and a max-level of `-9999`. I am sure that this would break the plugin as of current.

**Comment by lokka30** [comment]
My thought is to add `void validateSettings()` and `void validateMessages()` methods into ConfigUtils that run right after the configs are loaded.
In addition, config.options().copyDefaults(true) should be used.

**Comment by stumper66** [comment]
I added some bullet proofing with my last 2.2.0 beta.  malformed custom drops.yml simply bypasses any custom drops and malformed settings.yml or messages.yml will show a graceful error message and disable the plugin.
