### ISSUE TITLE
Request: Level mobs according to player attributes

### ISSUE THREAD

**Issue by stumper66** [lokka30/LevelledMobs#142]
Suggested by Yаn#5602

> I saw in a few servers that the mobs are scaled based on the player stats (health, armor). I don't know how hard this can be, knowing that some servers (mine too) use plugins to modify the player stats with armors etc.

**Comment by lokka30** [comment]
> Suggested from Yаn#5602
> 
> I saw in a few servers that the mobs are scaled based on the player stats (health, armor).
> I don't know how hard this can be, knowing that some servers (mine too) use plugins to modify the player stats with armors etc

I have considered player-based-levelling in the past, however now this request has made me re-think it.
We can simply listen to EntityTargetEvent which only hostile mobs (I believe?) call, and increase the level if the user meets the requirements in health or armour as mentioned in the request.
This eliminates the need for async tasks etc.
I was thinking of a nice particle effect on mobs that got levelled up too. Possibly even a 'Level Up!' hologram for the fun of it. :)

**Comment by lokka30** [comment]
PAPI is being used in LM 3.1 in order to accomplish this, and beyond.

**Comment by lokka30** [comment]
This can be linked to #241 as well.

**Comment by lokka30** [comment]
Already done in LM 3.1.
