### ISSUE TITLE
Optional exponential and logarithmic levelling formula 

### ISSUE THREAD

**Issue by stumper66** [lokka30/LevelledMobs#143]
Suggestion from UltimaOath#1247

> A suggestion regarding the issue of changing the max level. Perhaps offer the ability to switch between different leveling standards, from the current incremental addition (linear) to optional exponential increase formula to perhaps logarithmic for the very high maxes like 100+
you would use the starting stats provided in the config and then apply the function depending on whether they want current (linear), exponential for difficulty, or logarithmic for high max levels basically

I was thinking about it and thought the logarithmic function would suite the higher max but issue was the speed; might suggest a hard cap on the speed so let it build in speed until the input cap is hit then it won't level that stat further? could be used for the other stats as well

**Comment by lokka30** [comment]
> Suggestion from UltimaOath#1247
> 
> A suggestion regarding the issue of changing the max level. Perhaps offer the ability to switch between different leveling standards, from the current incremental addition (linear) to optional exponential increase formula to perhaps logarithmic for the very high maxes like 100+
> you would use the starting stats provided in the config and then apply the function depending on whether they want current (linear), exponential for difficulty, or logarithmic for high max levels basically
> 
> I was thinking about it and thought the logarithmic function would suite the higher max but issue was the speed; might suggest a hard cap on the speed so let it build in speed until the input cap is hit then it won't level that stat further? could be used for the other stats as well

A min and max value for the 'additions' values are a great idea especially with these systems.

**Comment by UltimaOath** [comment]
The new Blended system is essentially this, or can be modified easily to do so. I think this is close-able.
