### ISSUE TITLE
Improved nametag visibility option

### ISSUE THREAD

**Issue by stumper66** [lokka30/LevelledMobs#144]
Requested by Matt_#0008 (and requested by others prior although refused).

Name tags should have an option 'in between' the true & false settings for CustomNameVisible, i.e. the tag shows when you can see the mob and are in range, rather than seeing it through blocks or only seeing it when in arms reach and looking at it.
This can be achieved with an async repeating task. It could put quite a bit of stress on the server so I am unsure if the feature should be implemented.

Consideration to make- spawner mobs should most likely not have this feature (or disabled by default) as mob farms will significantly affect the async task mentioned above.

**Comment by stumper66** [comment]
Currently if you remove protocollib the above behavior still exists, the only difference being just the nametag is displayed without level information.

I suggest if protocollib is not installed that we revert to 1.34 behavior where levelled information is set on the entity's custom nametag.
This would give user's the ability to effectively toggle between 2.0's packets system or 1.34's nametag system.

**Comment by stumper66** [comment]
Desired behavior as requested by Matt_ : 
https://images-ext-1.discordapp.net/external/kYJ9CimdaDu6xyZgjucuysH6BzxP-atZO2O8CY9mSFE/https/i.imgur.com/rcFRVXy.mp4

**Comment by JustAMatt** [comment]
Ideally what you'd want to emulate is Ranull's work here: https://imgur.com/rcFRVXy

Where the nametag is always visible **only** if there are no blocks between the player and mob.

That would be the ideal behaviour and should be doable with packet modifications from protocollib.

**Comment by lokka30** [comment]
I am very against even having the old system toggleable although it can happen if there is great reason to.

I don't see any useful threads on the web that could help us implement this system so I'll probably have to write one up

**Comment by lokka30** [comment]
Reading the title again brought a needed bugfix in mind - LM ignores whether the current nametag is CustomNameVIsible or not so I will fix that now.

**Comment by lokka30** [comment]
I apologise for my confusion. What's the 'bug'? Or, is this a feature request for the nametag hidden behind walls behaviour?
The 'nametag always visible' setting allows you to toggle between the modes Vanilla provides us, if that is what the report was asking for?

**Comment by JustAMatt** [comment]
Hello! It's not actually a bug, not sure why it was reported as such. It's more of a feature request to change the tag system from "only shows when hovering over" to showing whenever a mob is within sight range. So, if there are no blocks between the player and the mob = tags show.

**Comment by lokka30** [comment]
> Hello! It's not actually a bug, not sure why it was reported as such. It's more of a feature request to change the tag system from "only shows when hovering over" to showing whenever a mob is within sight range. So, if there are no blocks between the player and the mob = tags show.

Thank you very much for the clarification. :)

**Comment by lokka30** [comment]
Shifted to 'medium priority', feel free to change that back if you want stumper.

**Comment by lokka30** [comment]
I have created a new issue for this, which is 100 issues newer 😄 
#144 to #244.
I did this as there was a lot of clutter caused by confusion and an assortment of different issues being raised inside this issue which could blur the requester's intent. I have also vastly elaborated on the issue so it is clear what the issue is, how we can solve it, and other things we can do with the proposed system.
