### ISSUE TITLE
Add Levelling Strategy: 'Ender Dragon Kill Count'

### ISSUE THREAD

**Issue by stumper66** [lokka30/LevelledMobs#145]
Suggested by: `Hugo5551`

This makes the ender dragon's level depend on the amount of times it has been killed.

**Comment by lokka30** [comment]
I assume that it will be difficult to make the ender dragon more difficult besides making it do more damage, even then, the ender dragon is not a difficult boss damage-wise so I am unsure how we will make the ender dragon more difficult

**Comment by lokka30** [comment]
See #242

**Comment by UltimaOath** [comment]
We can look at ender dragon plugins for inspiration on how to improve the
dragon fight. I think the ender dragon and eventually the warden will be
good 'boss' style creatures which could provide a path towards making a
boss system which could add new conditions, abilities, and alike to the
rules system overall that would work best for a boss but could be used
anywhere like the other configs can.

**Comment by lokka30** [comment]
added to brainstorming actions file
