### ISSUE TITLE
Tiered level suggestions

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#147]
Idea: Adding in tiered gear drops. The higher the level of mob, the better the gear drops become. Perhaps adding in coloured name tags to the mobs, the higher tiered ones are in red, middle tier gold and low, easy mobs in green.

https://www.spigotmc.org/threads/levelledmobs-for-1-14-x-1-16-x.412953/page-9#post-4071220

**Comment by stumper66** [comment]
This can be accomplished with custom drops in 2.1.0 using min and max level requirements

**Comment by lokka30** [comment]
I will make the following a separate issue:
> Perhaps adding in coloured name tags to the mobs, the higher tiered ones are in red, middle tier gold and low, easy mobs in green.

> https://www.spigotmc.org/threads/levelledmobs-for-1-14-x-1-16-x.412953/page-9#post-4071220
