### ISSUE TITLE
Mobs not spawning with max hp

### ISSUE THREAD

**Issue by soloman981** [lokka30/LevelledMobs#15]
So i started to use the plugin and everything seems to be working fine but the only problem is that mobs spawn always with default minecraft hp 
for example a level 8 zombie will spawn with 20/28 hp
there are no errors in log files and im using 1.15.2 spigot

**Comment by lokka30** [comment]
Hi! Thanks for reporting the issue.
The latest version should fix this. 
If you've got the latest version, then make sure your config is updated.
Please reply to the issue if changing to the latest version does help.

**Comment by Fred-Smashing** [comment]
I'm having the same issue, Zombie level 62 has 82 max health but only spawns with 20, I can use potions to heal him to his max, but for some reason it doesn't set the max health when they spawn.
Tested it with and without any other plugins

**Comment by lokka30** [comment]
Interesting. Once again, is your config and plugin definitely up to date? I'll investigate this.

**Comment by lokka30** [comment]
Ah, I've analysed the code and I think I've found the problem.
LMobSpawn.java, line 70, it sets the max health to the previous max health, not the levelled one. Oops!
New version will be uploaded soon

**Comment by lokka30** [comment]
Bam :) [Updated.](https://www.spigotmc.org/resources/%E2%98%85levelledmobs%E2%98%85-a-simple-drag-n-drop-solution-for-mob-attributes.74304/updates)
