### ISSUE TITLE
Custom drops meta and attributes

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#150]
> How about adding customizable names and lores to custom drop items? And maybe some attributes such as armor toughness or any others

https://www.spigotmc.org/threads/levelledmobs-for-1-14-x-1-16-x.412953/page-9#post-4071693

**Comment by stumper66** [comment]
This has been added to 2.2.0 as of PRE 5

**Comment by lokka30** [comment]
Previously tested by stumper
