### ISSUE TITLE
Add setting to have summon command to ignore max level setting

### ISSUE THREAD

**Issue by stumper66** [lokka30/LevelledMobs#153]
Submitted by Leasoncre#7439

> a simple config option like spawn-command-allows-over-max-level: true
> alternatively, or additionally, you could set a permission node to allow it(with level specification). (depends how admins want to manage that, if at all)

I was considering the more advanced folks, that might want mods limited to level 20, admins limited to level 50, but ops/owners any level for example

**Comment by lokka30** [comment]
The config option suggested,

> spawn-command-allows-over-max-level: true

is perfect in my eyes. I don't believe the multiple 'limit' permission nodes are necessary, but a single 'bypass' permission node would only take a few seconds to add.

**Comment by lokka30** [comment]
@stumper66, is this suggestion the same as the `/override` argument you added?

**Comment by stumper66** [comment]
It's already present in 2.3 beta you can use /overwrite when summons is being used to override any rules.

**Comment by lokka30** [comment]
Working
