### ISSUE TITLE
Money rewards for killing a mob via Vault

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#158]
Requested by mimilek89#3327 via a ticket on the discord

**Comment by UltimaOath** [comment]
Potentially do-able now through the CustomCommands system integrated into CustomDrops presuming their economy plugin has commands to send money to players (never knew one that didn't). They could use the ranged tag created to have a random amount of money as well :) . I believe this is close-able.

**Comment by lokka30** [comment]
> 
> 
> Potentially do-able now through the CustomCommands system integrated into CustomDrops presuming their economy plugin has commands to send money to players (never knew one that didn't). They could use the ranged tag created to have a random amount of money as well :) . I believe this is close-able.

Absolutely. It would be best to avoid adding integrations where not required (since commands can achieve this).
