### ISSUE TITLE
Make Tiered Coloring Configurable

### ISSUE THREAD

**Issue by stumper66** [lokka30/LevelledMobs#161]
Suggested by UltimaOath#1247

An example of how it could be configured:

tieredcolor:
  tier1:
    color: 4
    range: 0-20
  tier2:
    color: c
    range: 21-40
  tier3:
    color: 6
    range: 41-60
  tier4:
    color: e
    range: 61-80
  tier5:
    color: a
    range: 81-100

With the unused tiers ignored, anything outside of the range

**Comment by lokka30** [comment]
Unsure if this should be a 2.5 issue or 2.6 issue. Possibly 2.7, as 2.6 will be a busy update.

**Comment by stumper66** [comment]
Added to 3.0 b387.  Used the following syntax:
```
  tiered-coloring:
    1-3: '&a'     # green
    4-6: '&e'     # yellow
    7-10: '&c'    # red
    default: '&1' # dark blue
```

**Comment by BenjaminHoegh** [comment]
would it be possible to add the opportunity to add two colors for each tiered, this will allow more custom name tags

**Comment by UltimaOath** [comment]
> Added to 3.0 b387. Used the following syntax:
> 
> ```
>   tiered-coloring:
>     1-3: '&a'     # green
>     4-6: '&e'     # yellow
>     7-10: '&c'    # red
>     default: '&1' # dark blue
> ```

Tested and verified working. 

> would it be possible to add the opportunity to add two colors for each tiered, this will allow more custom name tags

Are you referring to the gradient effect on text?

**Comment by BenjaminHoegh** [comment]
> > Added to 3.0 b387. Used the following syntax:
> > ```
> >   tiered-coloring:
> >     1-3: '&a'     # green
> >     4-6: '&e'     # yellow
> >     7-10: '&c'    # red
> >     default: '&1' # dark blue
> > ```
> 
> Tested and verified working.
> 
> > would it be possible to add the opportunity to add two colors for each tiered, this will allow more custom name tags
> 
> Are you referring to the gradient effect on text?

No, i think it would be nice to be able to change the colours of the text and give the brackets another color depending on the tier

**Comment by UltimaOath** [comment]
So talking it over with the devs there's currently not a lot of interest in expanding the tiered-coloring system at the present moment. One of the goals of LM is to keep the bloat to a minimum, as well as provide features which will be actively used by the community as a whole; and there's concern that adding a secondary color might do just that. The idea isn't being abandoned, just added to the drawer called "when there's nothing left for LM but to go big or go home" section. Thanks for the suggestion though!

**Comment by BenjaminHoegh** [comment]
> So talking it over with the devs there's currently not a lot of interest in expanding the tiered-coloring system at the present moment. One of the goals of LM is to keep the bloat to a minimum, as well as provide features which will be actively used by the community as a whole; and there's concern that adding a secondary color might do just that. The idea isn't being abandoned, just added to the drawer called "when there's nothing left for LM but to go big or go home" section. Thanks for the suggestion though!

its okay, i found a workaround

**Comment by lokka30** [comment]
Unfortunately we will refuse this feature request, as Oath said, we don't believe many people are going to utilise the feature in consideration to the code we will need to add and the migration of existing configs to accommodate the changes. Please let me know if you have any comments regarding the closure of this issue.
Thank you for the request, please send us any more requests and we would be glad to check them out! :)
