### ISSUE TITLE
Hex colors not working since v2.0.0

### ISSUE THREAD

**Issue by stumper66** [lokka30/LevelledMobs#164]
Submitted by Matt_ #0008

This section of the config doesn't implement hex colors (levelledmobs 1 accepted this format) (see attachment and screenshot)

Not working since 2.x
![image](https://user-images.githubusercontent.com/18266662/108305106-f83caf80-716e-11eb-92a9-a3a34c4e1904.png)

![image](https://user-images.githubusercontent.com/18266662/108305115-fbd03680-716e-11eb-94c6-ec0e32a6c526.png)

**Comment by lokka30** [comment]
Added to the [to-do list](https://trello.com/b/xAVFFEXQ/plugins-to-do-list) for MicroLib specifically.

**Comment by lokka30** [comment]
Done.

**Comment by lokka30** [comment]
Test if hex colors are working

**Comment by lokka30** [comment]
Working: https://prnt.sc/10e2wi7
