### ISSUE TITLE
Separate BABY_DROWNED from BABY_ZOMBIE

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#165]
Suggested by Oath
https://discord.com/channels/752310043214479462/757933745620779033/813004679964393502

**Comment by UltimaOath** [comment]
For reference:
https://minecraft-archive.fandom.com/wiki/Baby_Mobs
A list of baby mobs which are potentially spawnable.

**Comment by lokka30** [comment]
> For reference:
> https://minecraft-archive.fandom.com/wiki/Baby_Mobs
> A list of baby mobs which are potentially spawnable.

I believe I have solved this issue actually. I haven't been able to test it yet
