### ISSUE TITLE
Levelling System Revamp

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#170]
As suggested by Oath, we should allow levelling systems to be prioritised in `settings.yml`. Furthermore, there are likely to be more things Oath has suggested regarding the levelling system being updated, but they seem to have gotten lost.

very basic e.g.:
```
levelling-systems:
- WORLD_OVERRIDE
- ENTITY_OVERRIDE
- SPAWN_DISTANCE_LEVELLING
- Y_DISTANCE_LEVELLING
- WEIGHTED_RANDOM
- RANDOM
```

World override is priorised over entity override, and so on.

**Comment by UltimaOath** [comment]
My remarks related to levelling-systems-priority

priority: #suggested order
  - ENTITY
  - WORLD
  - GLOBAL
  - SPAWNDISTANCE
  - YDISTANCE
  - WEIGHTED_RANDOM (not my suggestion so idk where to place)
  - RANDOM (presume it would just pick a random priority list?)

And then the final regarding this was to make sure and update settings.yml with the final terminology LN630

**Comment by lokka30** [comment]
@UltimaOath @stumper66 Should this be added *this* update, or *next* update?

**Comment by UltimaOath** [comment]
I can update the config for pretty pretty anytime; Stumper's baby he can decide :)

**Comment by stumper66** [comment]
Since this is flagged as high-pri I'll add it to 2.3.  About to start now

**Comment by lokka30** [comment]
I believe I will also be working on this system in ~8-9 hours from now. I aim to improve the code for the levelling systems significantly.

**Comment by lokka30** [comment]
Closed since new system is being planned.
