### ISSUE TITLE
add 'variance with chance' system

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#172]
https://www.spigotmc.org/threads/levelledmobs-for-1-14-x-1-16-x.412953/page-10#post-4098613

Add a separate variance system that makes mobs higher levels with a certain chance, e.g. 5% chance to spawn mobs 5 levels higher than usual in distance from spawn levelling.

**Comment by UltimaOath** [comment]
This funnily enough can be done now in LM3 with a custom-rule, using the `chance:` condition to create a custom entity. I believe this is close-able.

**Comment by lokka30** [comment]
Even if it isn't feasible with the rules system, I think this suggestion is a bit bloat-y. I'll close it but it can be revisited in the future if required.
Since the rules system should cover this, then should be good!
