### ISSUE TITLE
Levelled mob spawners

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#179]
> I would love a way to create a monster spawner with adjustable levels

Suggested by hyper#0001

**Comment by UltimaOath** [comment]
Isn't this already doable with worldguard flags?

**Comment by lokka30** [comment]
> Isn't this already doable with worldguard flags?

Good point - you can set WorldGuard regions around the spawners. Not exactly what they're looking for, but I'll let them know. This is low-priority regardless so I don't believe it will be added ever (if ever).

**Comment by stumper66** [comment]
This has been added to LM 3.0
