### ISSUE TITLE
Custom drops not reloading properly

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#181]
When I run /lm reload, it doesn't seem that the custom drops are being reloaded. Re-starting the server works.

**Comment by lokka30** [comment]
Fixed in b300, tested. Would like a comment from @stumper66 since it's his baby, unsure if I have fixed it in the correct manner.

**Comment by stumper66** [comment]
I looked at the b300 changes.  It would appear I broke customdrops reload when I added the customdropshandler class.
Looking at the revisions you made I believe that will fix it.

**Comment by lokka30** [comment]
> I looked at the b300 changes. It would appear I broke customdrops reload when I added the customdropshandler class.
> Looking at the revisions you made I believe that will fix it.

Thanks for the reply. Glad it was a simple fix :)
