### ISSUE TITLE
Request: Implement more customisable attributes (vanilla, not custom)

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#185]
> On a separate note while I was browsing the attributes system, I think adding in some of the other attributes to the system would be worth-wild, including follow_range, knockback_resistance, armor, armor_toughness, and attack_knockback. Could still apply the 'use 0 for disable' to all these settings as well. All can be set to zero by default; just added customization

Suggested by @UltimaOath in the Discord server.

***

These attributes should be disabled (set to `0`) by default. The administrator can configure them if they wish.

**Comment by UltimaOath** [comment]
I think this might be a worth Wild next feature to focus on for the simple fact that including things like armor and attack knock-back what allow 4 a change to the default configuration where I can reduce the current values a bit and supplement with commented out values for the new features that would still provide the difficulty we'd expect while making things a bit easier for those unwilling or unable to modify

**Comment by lokka30** [comment]
> 
> 
> I think this might be a worth Wild next feature to focus on for the simple fact that including things like armor and attack knock-back what allow 4 a change to the default configuration where I can reduce the current values a bit and supplement with commented out values for the new features that would still provide the difficulty we'd expect while making things a bit easier for those unwilling or unable to modify

I believe these extra attributes don't contribute much to gameplay but "may as well" add them in since Minecraft has them there for us :)

**Comment by stumper66** [comment]
Added to LM 3.2.0 b511
