### ISSUE TITLE
Allow NBT Data in CustomDrops

### ISSUE THREAD

**Issue by stumper66** [lokka30/LevelledMobs#195]
Suggested by NordLord#7525

Can we put NBT data in the Material name / is there a field for adding NBT data to items dropped?

Trying to make a vanilla friendly super hostile zone in my world where all mobs are super high level and have a chance to drop a random piece of unbreakable gear using {Unbreakable:1b/0b}, and I also had an idea for making event "bosses" that dropped a random set of decorative head furniture via {SkullOwner:"player name"}

The Unbreakable tag is a status symbol in this case because Mending already makes your tools effectively unbreakable, as would Unbreaking XXXXX, but not having a durability bar is what makes it special.

Data field could make it easier to integrate drops from other plugins in it as well, and pre-written books.. or whatever else really. I'm not a developer so I don't know the deepest reaches of something like that.

**Comment by lokka30** [comment]
Was this already added @stumper66 ?

**Comment by stumper66** [comment]
Not yet.  I might be able to squeeze it into 3.0 within the next few builds.
Worse case scenario it goes in 3.1

**Comment by lokka30** [comment]
Don't fret about it now - unless you want it in v3.0 specifically 🙂

**Comment by UltimaOath** [comment]
Feature included as of LM3.0.4 b444 ; Utilizes NBT-API https://www.spigotmc.org/resources/nbt-api.7939/ as soft-dependency for any NBT related function within LM.
