### ISSUE TITLE
add aureliumskills support for custom drops

### ISSUE THREAD

**Issue by stumper66** [lokka30/LevelledMobs#196]
Suggested by zaspany kuba#6655

Hi! Is there any way to connect levelledmobs with AureliumSkills?
I mean, is there any way to levelledmobs drop items with aureliumskills modifier?

look, aureliumskills is plugin that add skills etc. Its also adds modifiers to armor/weapons
Its look like that (attached screenshot)
![aureliumskills](https://user-images.githubusercontent.com/18266662/112905299-cdb80d80-90af-11eb-83c1-820928ccace9.png)

Possibly adding NBT support (issue #195 ) will solve this as well.

**Comment by stumper66** [comment]
zaspany kuba — Today at 5:04 PM
I talked with dev of aureliumskills and he said that custom nbt will solve this problem

**Comment by lokka30** [comment]
As stated above, #195 will solve this. Closing this issue.
