### ISSUE TITLE
Request: Levelled spawn eggs

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#197]
https://www.spigotmc.org/members/british89.355307/ suggested:

> Would be amazing if you could do /lm egg [ENTITY] [LEVEL] to get a mob of any level in an egg for mob arenas

Link to suggestion: https://www.spigotmc.org/threads/levelledmobs-for-1-14-x-1-16-x.412953/page-11#post-4125137

Initial thoughts: need to listen for hand-placement, dispencing of the eggs. Possibly warn users when they click on spawners with it

**Comment by UltimaOath** [comment]
Thinking if we replicate the system for producing Spawners, but use it to produce Eggs.

**Comment by lokka30** [comment]
Already assigned to LM 3.2 through the Projects tab - if 3.3 is desired then please change the target project of this issue rather than using labels :) (let me know if there's an issue with it)

**Comment by UltimaOath** [comment]
The labels were for Penal's benefit he asked me to mark things

**Comment by lokka30** [comment]
All issues without the `unassigned target version` label have a Project assigned to them already. A new Project is created for each version that is being maintained and also each planned version - so we've got 3.2, 3.3, 3.4, 4.0, etc.

The projects system is far better than the labels and milestones setup we had previously for a bunch of reasons. But if you guys have any issues with it please let me know.

**Comment by stumper66** [comment]
Added to LevelledMobs v3.3.0 b568

**Comment by UltimaOath** [comment]
Tested and working in b578
