### ISSUE TITLE
WorldGuard scaling for each region

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#2]
per region support (worldguard) with scaling level for each region
Suggested by discord: Ash#4073

**Comment by lokka30** [comment]
currently out of my skill level to work with WG, won't be added until later on

**Comment by lokka30** [comment]
Eyrian's pull includes min/max level, but not scaling. I doubt this feature would be used by many but I'll leave it here anyways.

**Comment by Eyrian2010** [comment]
What should be scaled? I can expand the functionalities.

**Comment by lokka30** [comment]
Min/max level can have functionality which I expect from the requester would do the same job.
