### ISSUE TITLE
Check if 're-level mob on tame' is even required

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#200]
I believe taming mobs doesn't re-spawn the entity and thus I don't think it will have to be 're-levelled' as it currently is.

Any thoughts on this @stumper66? If not, I'll get to testing. :)

**Comment by UltimaOath** [comment]
I have tested this in game with wolves and donkeys; console output:
[INFO]: LevelledMobs: [DEBUG] [EntityTameListener] no-level-conditions.tamed = true
[INFO]: LevelledMobs: [DEBUG] [EntityTameListener] Removed level of tamed mob

**Comment by lokka30** [comment]
Elaboration on the issue: I am unsure if pets lose their level once they have been tamed. Currently it seems to me that they don't, but we are re-levelling the pet anyways, which might be unnecessary. No-level-conditions is working as intended :)

**Comment by UltimaOath** [comment]
It specifically says that the level was removed from the tamed mob?

**Comment by lokka30** [comment]
> It specifically says that the level was removed from the tamed mob?

Separate feature doing its job properly :) I believe you're thinking of the wrong thing


According to the LM code, animals lose their level when they are tamed. I don't think this is the case, so I want to test that. I don't want mobs to be unnecessarily re-levelled, if they retain their level in the first place.

**Comment by lokka30** [comment]
Tested: they do require re-levelling. 🤷🏻
