### ISSUE TITLE
Levelled mob spawners

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#204]
Suggested by AbisGamer#0001

Administrators should be able to create custom spawners which spawn Levelled Mobs instead of normal mobs. For example, a spawner in a dungeon could spawn Level 10 Zombies only, holding a netherite sword and with full iron protection 5 armor.

Please request an elaboration if you are interested about this issue.

**Comment by stumper66** [comment]
This has been added to LM 3.0

**Comment by lokka30** [comment]
Duplicate issue, see #179
