### ISSUE TITLE
CustomDrops: improve equippedspawnchance

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#205]
> remove equippedspawnchance and simply replace the equipped true/false with a percent chance. Could translate a true to 1.0 and a false to 0.0 when converting, and simply use the equipped value if it's anything other than 0 process the equip chance? Would also eliminate the extra value and bring it to a shorter value

Suggested by oath

**Comment by UltimaOath** [comment]
Tested in b360, was functioning as intended.
