### ISSUE TITLE
Kill command: add '/nodrop' for 'near'

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#206]
> /nodrop appears to work as intended in all, though I would suggest including the function /lm kill near <radius> /nodrop for similar reason.

Suggested by oath

**Comment by stumper66** [comment]
added to 2.6.0 b379

**Comment by lokka30** [comment]
@stumper66 - is there a reason this issue is still open? I think we may have forgotten to close it. 😄
