### ISSUE TITLE
Request: Allow LM Labels on non-levelled mobs

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#212]

**Comment by lokka30** [comment]
In summary, some users have suggested that the LevelledMobs nametag system should also apply nametags to non-levelled mobs.

**Comment by UltimaOath** [comment]
Maybe another configure option under that setting? applyToNonLevelled: false/true

**Comment by lokka30** [comment]
Outside of the scope of the plugin. Unsure if we should add this in. @stumper66 @UltimaOath any thoughts?

**Comment by UltimaOath** [comment]
Personally I like the idea of being able to use LM's nametag system without
necessarily applying a level. It'd be useful for some I could see, mostly
for visuals though. I also don't think it would require much on our part;
basically a `nametag-nonlevelled:` setting which functions like the regular
nametag: config, then a secondary enable/disable mechanism to enable the
nonlevelled tags.

**Comment by stumper66** [comment]
Agreed, don't think it would take much effort to enable it.  I'll look into it for 3.1.

**Comment by lokka30** [comment]
Okay thank you two for the inputs. Feel free to adjust this issue's milestone if you see fit. :)

**Comment by lokka30** [comment]
Regarding the recent label added for Very Low Priority: if #244 is added and as a separate plugin, it is very likely that this issue will also be solved.

**Comment by UltimaOath** [comment]
As a note I was thinking since we use LVL 0 as the 'not levelled' state, what if there was a `lvl_0_nametag: '%displayname%` which would only apply under the set conditions to level 0 entities, aka the ones that wouldn't be levelled.

**Comment by lokka30** [comment]
I really think this is out of the scope of the plugin. This feature will also create compatibility issues with other plugins.

**Comment by UltimaOath** [comment]
I only bring it up again because we already have a config for non levelled
entities to get a name with a placeholder, so thought optional availability
via nametag the next logical step since the process is already there.

**Comment by lokka30** [comment]
I think we can facilitate the feature but users should not expect any miracles.

**Comment by lokka30** [comment]
Nope.
