### ISSUE TITLE
Request: Improved debugging for 'BABY' mobs

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#214]
UltimaOath suggests:

>` [01:07:36 INFO]: LevelledMobs: [Debug: APPLY_LEVEL_FAIL] Entity ZOMBIE in world world was not levelled -> Levellable state: DENIED_CONFIGURATION_BLOCKED_ENTITY_TYPE` This is the debug message when applied to the baby variants. Any chance we could add the note that it was infact a BABY_ zombie?

**Comment by stumper66** [comment]
Added to 3.0.0 b395

**Comment by UltimaOath** [comment]
Tested in b409; functions as intended.
