### ISSUE TITLE
Request: Option For CustomDrops To Only Drop When Killed By A Player

### ISSUE THREAD

**Issue by stumper66** [lokka30/LevelledMobs#216]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Option for mobs to only drop custom drops when killed by a player

**Describe alternatives you've considered**

**Additional context**
Suggested by wv4tcrtacactxwytv#2863

**Comment by stumper66** [comment]
This was added to 2.6.0 b379 (now 3.0)

**Comment by UltimaOath** [comment]
Tested; functions as intended in b409
