### ISSUE TITLE
Request: 'scan' subcommand

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#217]
`/lm scan` should be added, this will go through every entity that the server has currently loaded and it will level it if it is deemed levellable.
This will not be a repeating task or anything, just a manual command, to save performance *significantly*.

**Comment by stumper66** [comment]
Will this re-level already levelled mobs?
Will it unlevel mobs that have been levelled if the rules have changed?

**Comment by lokka30** [comment]
> Will this re-level already levelled mobs?

perhaps this can be an optional argument in the command. by default, it shouldn't re-level mobs, only level unlevelled mobs that are supposed to be levelled

> Will it unlevel mobs that have been levelled if the rules have changed?

would use the same argument I mentioned prior

**Comment by lokka30** [comment]
added already as `force_all`
