### ISSUE TITLE
LM 3.0 Testing

### ISSUE THREAD

**Issue by stumper66** [lokka30/LevelledMobs#224]
- [ ] Testing custom-mob-level and it appears that the settings for entities are overwriting the default values for all entities it appears
So the custom-mob-level multipliers appear to overwrite the regular multipliers for all entities regardless.

- [ ] PLAYER_HEAD as a drop does not respect the setting in settings.yml mobs-multiply-head-drops ; though technically it's an item and could have no-multiplier applied but I personally believe since it's still a head it would match setting. get your opinion on it

- [x] I like how if mobhead-id/texture isn't specified it defaults to the entity itself, however when it does this the entity holds that head block in their hand when equipped rather than on it's head as it would have done with a custom/textured block.
Love the feature though this allows for unique mob heads for different biomes and alike :3

- [x] Noticed when name: isn't specified for PLAYER_HEAD that it defaults' to an all caps version of entity's name in italics, ie HUSK. I'd say that the default name should be left blank since depending on the head being dropped the name would prob. have no connection to the entity. It also currently causes the situation where if multiple entities wear the same head without name declared it will leave duplicate heads  with different names filling inventory.

- [x] Separately I think being able to use a %entity% name which will fill in the entity's name like Husk. ie name: 'Platinum %entity% Skull'
This will allow for the following:
name: blank or not included defaulting to a blank/empty name slot.
name: '%entity% for the default text for that entity skull.
name: 'Uncommon %entity% Skull' for unique skull still incorporating entity's name.
This would mostly be useful for the groups' section, like if I wanted to have an event where all levelled entities dropped this one kind of special head but with each entity having it's own text applied.

- [x] The above %entity% tag good for the customCommands as well.
- [x] We def! need to except the customCommand from when we kill entities with the kill command. Will spam the console and depending on the kind of command will potentially crash with every death when player-caused: false or not specified.
- [x] The amount: default for customCommands does not appear to have a function. Can you clarify

**Comment by UltimaOath** [comment]
- [ ] 'BABY_' ; when used in entity list, will apply to all baby variants of entities. Useful for blacklisting movement speed on the baby entities, or simply not levelling any of the babies for flavor (gaining level as adult).

**Comment by UltimaOath** [comment]
- [ ] Biome Universal Groups
SNOWY_BIOMES
- SNOWY_TUNDRA
- ICE_SPIKES
- SNOWY_TAIGA
- SNOWY_TAIGA_MOUNTAINS
- SNOWY_TAIGA_HILLS
- FROZEN_RIVER
- SNOWY_BEACH
- SNOWY_MOUNTAINS

COLD_BIOMES
- MOUNTAINS
- GRAVELLY_MOUNTAINS
- MODIFIED_GRAVELLY_MOUNTAINS
- WOODED_MOUNTAINS
- TAIGA
- TAIGA_MOUNTAINS
- TAIGA_HILLS
- GIANT_TREE_TAIGA
- GIANT_TREE_TAIGA_HILLS
- GIANT_SPRUCE_TAIGA
- GIANT_SPRUCE_TAIGA_HILLS
- STONE_SHORE

TEMPERATE_BIOMES
- PLAINS
- SUNFLOWER_PLAINS
- FOREST
- FLOWER_FOREST
- BIRCH_FOREST
- BIRCH_FOREST_HILLS
- TALL_BIRCH_FOREST
- TALL_BIRCH_HILLS
- DARK_FOREST
- DARK_FOREST_HILLS
- SWAMP
- SWAMP_HILLS
- JUNGLE
- MODIFIED_JUNGLE
- JUNGLE_HILLS
- MODIFIED_JUNGLE_EDGE
- BAMBOO_JUNGLE
- BAMBOO_JUNGLE_HILLS
- RIVER
- BEACH
- MUSHROOM_FIELDS
- MUSHROOM_FIELD_SHORE
- WOODED_HILLS

DRY_BIOMES
- DESERT
- DESERT_LAKES
- DESERT_HILLS
- SAVANNA
- SHATTERED_SAVANNA
- SHATTERED_SAVANNA_PLATEAU
- BADLANDS
- ERODED_BADLANDS
- WOODED_BADLANDS_PLATEAU
- BADLANDS_PLATEAU
- SAVANNA_PLATEAU
- MODIFIED_BADLANDS_PLATEAU
- MODIFIED_WOODED_BADLANDS_PLATEAU
- MODIFIED_SAVANNA_PLATEAU

OCEAN_BIOMES
- WARM_OCEAN
- DEEP_WARM_OCEAN
- LUKEWARM_OCEAN
- DEEP_LUKEWARM_OCEAN
- OCEAN
- DEEP_OCEAN
- COLD_OCEAN
- DEEP_COLD_OCEAN
- FROZEN_OCEAN
- DEEP_FROZEN_OCEAN

NETHER_BIOMES
- NETHER_WASTES
- CRIMSON_FOREST
- WARPED_FOREST
- SOUL_SAND_VALLEY
- BASALT_DELTAS

END_BIOMES
- THE_END
- SMALL_END_ISLANDS
- END_MIDLANDS
- END_HIGHLANDS
- END_BARRENS

**Comment by UltimaOath** [comment]
- [ ] Entities when given player_head will still hold head in their hand rather than equip onto head as intended.

**Comment by UltimaOath** [comment]
- [ ] Give presets system a once-over; been several instances where merging lists didn't appear to work as intended. No specific bug to report per say on this one.

**Comment by UltimaOath** [comment]
```
default-rule:
    name: 'WHITELIST - Default World List'
    conditions:
      worlds:
        mode: 'WHITELIST'
        list: ['world', 'world_nether']
```
```
custom-rules:
  - enabled: true
    name: 'Stage1 - WorldLimiter'
    conditions:
      worlds:
        mode: 'WHITELIST'
        list: ['world']
```

- [ ] It appears 'worlds' custom-rules do not apply, only the default-rule will. I've tried many variations including 'ALL' in default rule and blacklist/whitelist in custom-rule and it did not overwrite.

**Comment by UltimaOath** [comment]
- [ ] When using default rules.yml file (latest on Discord), if you enable levelling passive custom rule, the passive entities will level however they will not get a nametag. Tested with damage debug and shows that it got levelled with a null nametag.

**Comment by UltimaOath** [comment]
- [ ] When using customCommand drop, if I specify 'player-caused: false', the command will still run when the LM kill command is run, thus ignoring the limiter restriction. Needs to be exception for this particular config when used within customCommands only.

**Comment by UltimaOath** [comment]
- [ ] With entity-health-rounded, if the entities' health gets below 0.5 but not quite zero it will round down to zero, instead of displaying at least '1' health.

**Comment by UltimaOath** [comment]
- [ ] Useful needed feature: improve %ranged% by allowing the following:
```
  - customCommand:
      command: "effect give %player% strength %ranged_1% %ranged_b%"
      ranged_1: 2-5
      ranged_b: 0-2
      amount: 5
      chance: 1.0
```
The ability to list 'endless' amounts of ranged variables. Have it checked for 'ranged_' then grab the appendage and match to the tag in command for that ranged value.

**Comment by UltimaOath** [comment]
- [ ] A setting in settings.yml which allows the hiding of commands being run towards the player. Basically when I kill an entity I tested with an effect application, and when it worked it sent me the console 'applying effect on player' message. I remember there being some easy option to disable sending notices to the client and keep in console. Long story short a setting to enable/disable this feature ( thinking enabled prob default to hide commands running ).
