### ISSUE TITLE
Request: Add PAPI (PlaceHolder) Support

### ISSUE THREAD

**Issue by stumper66** [lokka30/LevelledMobs#225]
Requested by Eatruse#8768

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I'd like to add PAPI support so I can get the level of the mob from a placeholder

**Describe alternatives you've considered**

**Additional context**
Eatruse
I try to make a broadcast for killing a mobs. But I cant find the setting. 
But when a player killed by a mobs, its broadcast creature-death-nametag: '&8[&7Level %level%&8 | &f%displayname%&8]'
how do I enable killing mobs broadcasting?

**Comment by lokka30** [comment]
We have already considered this: PAPI seems to be an API orientated towards getting data from players, or getting data of a global variable e.g. 'total server balance'. This leads me to believe that PAPI is no good for LM.

Please prove me wrong if you can as I would desire LM->PAPI, so long it is viable :)

**Comment by lokka30** [comment]
My question to the requester is,

> What application would you use these PAPI placeholders in?

**Comment by UltimaOath** [comment]
I think the desire was to match it with a plugin which would modify their player death messages beyond changing the name of the entity. IE '[Dungeon LVL 7] Lokka couldn't avoid the Skeleton's arrow!' or something similar.

**Comment by lokka30** [comment]
> 
> 
> I think the desire was to match it with a plugin which would modify their player death messages beyond changing the name of the entity. IE '[Dungeon LVL 7] Lokka couldn't avoid the Skeleton's arrow!' or something similar.

I am quite certain that PAPI is not a solution for this. The LM API would need to be accessed to gain this information.
