### ISSUE TITLE
Request: Tag view distance

### ISSUE THREAD

**Issue by BenjaminHoegh** [lokka30/LevelledMobs#230]
An option to set the name tag view distance, so you can narrow down how many mobs you see when using `creature-nametag-always-visible`. I saw this be done in [TAB](https://www.spigotmc.org/resources/tab-1-5-x-1-17-free-version.57806/) and I think it makes sense to add this to LevelledMobs as well

**Comment by UltimaOath** [comment]
This is a long desired and reported item however limitations in Minecraft itself limits us. The method you suggest is typically reserved for limited use (if applied to a server full of entities constantly checking for any player near them and adjusting packets accordingly would be a huge resource commitment) and/or Player tags (handled differently than entity tags).

If you or know someone who has the skills to get over this mountain send them our way!

**Comment by lokka30** [comment]
We have got a similar (better?) idea at #144. For now I will close this issue but let me know if it isn't as good as what you wanted. :)
