### ISSUE TITLE
Request: Make all keys inside yml files case in-sensitive

### ISSUE THREAD

**Issue by stumper66** [lokka30/LevelledMobs#231]
**Is your feature request related to a problem? Please describe.**
All yml file parsing should be case in-sensitive when parsing

**Describe the solution you'd like**
MINLEVEL and mInLeVeL should work the same in rules.yml and customdrops.yml

**Describe alternatives you've considered**
None

**Additional context**

**Comment by UltimaOath** [comment]
I second the motion lol had lots of issues so far related to this
particular issue.

**Comment by lokka30** [comment]
@stumper66 @UltimaOath Was this fixed?

**Comment by UltimaOath** [comment]
Listed as fixed in 3.1.0  b447 ; I personally have not tested not sure if
Penal has or not. If not, I can make sure it's tested out on Monday/Tuesday.

**Comment by UltimaOath** [comment]
Tested in b455; Didn't test every possibility but overall the system works as intended.
