### ISSUE TITLE
Bug: Attribute values possibly not being applied as per the formula

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#234]
> lookaparrot — Today at 06:49
> Hello again ! I had a question regarding the attribute multiplier. The formula being used is, 
> 
> "newAttributeValue =                                                               |
 > |        | ( vanillaAttribute x configValue ) x (( entityLevel - 1) / maxLevel ) "
> 
> Let's say I set the max health multiplier to 7 and min_level to 1 and max_level to 2.
> 
> If a entity (skeleton) Lvl 1 has 20 health. Then a Lvl 2 skeleton should have,
> (20*7) * ((2-1)/2) = 140*0.5 = 70 health. What am I missing here?
> 
> Because this does not go in line with "For example, if 'max-health: 2.0', then                |
>  |        | an entity at maximum level will have a 200% increase in health.  ". Further, in game a Lvl 2 skeleton has 90 health under > the above setting.

At: https://discord.com/channels/752310043214479462/752312998571278497/858479218563219467

**Comment by UltimaOath** [comment]
Fixed in 3.0.4 b444

**Comment by lokka30** [comment]
Should we leave the issue open to update the documentation @UltimaOath ?

**Comment by UltimaOath** [comment]
I wouldn't worry the documentation has a lot of miscellaneous stuff to add going to be done in next day or two.
