### ISSUE TITLE
Request: Adjustable LM Spawner Range Value

### ISSUE THREAD

**Issue by UltimaOath** [lokka30/LevelledMobs#238]
Suggestion: Make adjustable the distance an entity can spawn from a LM Spawner. By default, the range is 16 blocks, but coulld be potentially adjusted with a `/range X` variable added to the LM Spawner command?https://discord.com/channels/752310043214479462/829238692161781770/861638031072428032

**Comment by lokka30** [comment]
Don't LM spawners use vanilla mechanics? 16 blocks is very far!

**Comment by lokka30** [comment]
@UltimaOath ^ please could you elaborate on this issue? I can't understand the original requester's intentions.

**Comment by UltimaOath** [comment]
If memory serves the basics being more config on the spawner system things
like adjustable spawn distance from the spawner (default is like 5 blocks I
think) among any other adjustable like how penal set a custom particle
effect for LM spawner and such.

**Comment by lokka30** [comment]
In this case, if I am understanding you correctly, we are modifying Vanilla mechanics by doing the 'adjustable distance from the spawner'.
Not only is this a very niche issue, it will also modify vanilla mechanics and require a decent amount of programming to accomplish

**Comment by lokka30** [comment]
I will close this issue due to the above, please re-open if you wish.
