### ISSUE TITLE
Request: Re-fresh levelling system code.

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#243]
The levelling systems in LevelledMobs need to have their code cleaned up significantly, also being put into their own classes inheriting an interface so that common methods are being used to determine the level for mobs.
Ideally each levelling system resides in its own class in a package `levellingSystems`, e.g. `me.lokka30.levelledmobs.levellingSystems.DistanceFromSpawn`.
Derived from the conversation in #242.

Doing this will clean up the code, which in turn makes it easier to work on, and easier to understand from other developers. It's also great to go over code and give it a re-fresher anyways.
It will also make it less messy to implement new levelling systems such as #137 and the other systems I mentioned in #242.

The new levelling systems do not need to be implemented immediately after this is completed, although it will make the process for doing such far quicker and easier. I recommend LM 3.2 for this, and perhaps new levelling systems can be added later on, or even in the same version.

**Comment by UltimaOath** [comment]
Also with the switch to J11 we can utilize some version specific changes to
improve things overall.

**Comment by lokka30** [comment]
Issue encompassed by #282.
