### ISSUE TITLE
Add translatable level numbers

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#245]
I am surprised we have only received one request, ever, to be able to change the level-numbers in nametags. This is in issue #94, although I wish to extend that issue by allowing numbers to be completely user-customisable.

e.g.

```yaml
number-translations:
 1: '1'
 2: '2'
 3: '3'
```
and so on.

This will also make Issue 94 possible, plus more.

Made a new issue for this as it is a different request to what 94 was asking for, although it makes 94 directly possible.

**Comment by UltimaOath** [comment]
As a note if we're going this route could we include the ability to specify level ranges like:

```
1-5: 'Bronze'
6-10: 'Silver'
11:  'Gold'
```
etc.

**Comment by lokka30** [comment]
This is being worked on in LM v4.0.

**Comment by lokka30** [comment]
The code is done. just need to make the placeholders available, and test.

**Comment by lokka30** [comment]
> As a note if we're going this route could we include the ability to specify level ranges like:
> 
> ```
> 1-5: 'Bronze'
> 6-10: 'Silver'
> 11:  'Gold'
> ```
> 
> etc.

I didn't see this when developing the code. Should this be added in?

**Comment by lokka30** [comment]
Closed as it is added in LM 4 but happy to re-open if the above is addressed and turns out we should add the feature
