### ISSUE TITLE
Request: allow the CustomCommand tags to work for regular drops as well

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#246]
@UltimaOath requests:

* Could we allow the CustomCommand tags to work for regular drops as well?
* I had a user wanting to implement the` %mob-lvl%` and thought that the other tags might have use as well but when I tried it only displayed the text not the tag value so I assume those tags are presently only working for the commands.

**Comment by lokka30** [comment]
I am unsure as to what priority this issue should receive, so I will allocate it medium unless someone believes it deserves higher priority.

**Comment by lokka30** [comment]
Any idea for which version we should implement this? 3.1, 3.2, 3.3, 3.4? @stumper66

**Comment by stumper66** [comment]
Added to 3.2.0 b515
