### ISSUE TITLE
Add customisable attribute formulas 

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#249]
To further extend the capabilities of our rules system, we could offer the ability for users to specify their own formulas that will determine the attributes of mobs, per-rule.

This will necessitate the addition of the `/lm debug dump` command, which may/may not have been posted in the issue tracker as a separate issue. This is because our support team may need to consider if this feature is utilised or not.

We can utilise Redempt's [Crunch](https://github.com/Redempt/Crunch) library to accomplish this.

This feature should definitely use the current attribute formula as the default.

This feature may be difficult for non-advanced administrators to comprehend, so the plugin should not be too reliant on the feature, if possible.

**Comment by UltimaOath** [comment]
I like the idea; if implemented I'd suggest it as a levelling strategy under similar formatting:  
  
\`\`\`yml  
strategies:  
  formula:  
    etc  
\`\`\`  
If this is more focused on I'll put more effort into construction a feasible config arrangement. I imagine integrated PAPI support for it, plus prob. a similar system to the `ranged_` tags used in customCommands to create dynamic formulae. Also might need to experiment with different 'working' solutions, maybe even use LM's actual formulae to demonstrate it working.

**Comment by lokka30** [comment]
The system has been fully brainstormed (to my understanding) for LevelledMobs v4.0. The code that parses these attributes has not yet been started.
