### ISSUE TITLE
Other: LM 3.1 To-do List

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#250]
* credit author of `textures.yml` from LM2.
  * @lokka30 
  * pre-release

**Comment by lokka30** [comment]
# Changelog

# LevelledMobs v3.1.0 b???


​# Very Important Changes – README:

    LevelledMobs is no longer supported for versions 1.14.x and 1.15.x, although it may be still functional on that version. We will explain this change below if interested.

    LevelledMobs now requires at least Java 11. We will explain this change below if interested. Contact us if you are unsure what this is.

​# Full Changelog
## ​Ceasing 1.14.x and 1.15.x support

    These versions are considerably outdated. Minecraft 1.17 was released a few months ago, and 1.16 has been out for more than a year. You should make the switch!

    We made this change as Minecraft 1.16 gives us the ability to explore new features and make them available in default configurations, especially RGB Hex Colors which make name tags look far greater.

    Although LevelledMobs may still work on these outdated versions, we will not provide support for these versions and will not guarantee ideal functionality on those versions from LevelledMobs v3.1 and onwards.

​Bumping minimum Java version to Java 11

    If you’re running a 1.17 server, you don’t need to worry about this since you are running at least Java 16, so good on you for staying updated :)

    If you attempt to run LevelledMobs with a Java version prior to Java 11, then you will not even be able to run the plugin. Make sure you are running at least Java 11.

    A considerable amount of servers are still using Java 8 for whatever reason, I am guessing this is because hosting providers can’t be bothered to make Java 11 the default. There is no drawback with making the update to at least Java 11. If you are using a hosting provider, ask their support how to update your Java if it isn’t at least Java 11 already.

    This change has allowed the LevelledMobs team to take advantage of some nifty code additions that have been added into Java 9, 10 and 11, so we can improve the plugin’s code further. On top of adding new features, improvements and fixes, we are also trying to improve our existing code. This change will allow us to take it further!

## ​Player levelling

    @stumper66 has enhanced LevelledMobs yet again with a brilliant levelling system that takes LevelledMobs to another level.

    Player-levelling uses statistics derived from PlaceholderAPI placeholders to level mobs around players. Most plugins that offer statistics for players using PlaceholderAPI can now be used to level mobs around players!

    Note, that this feature is not enabled by default. You can enable it and configure it in rules.yml and settings.yml.

    It will automatically re-level mobs if different players are closer to it.

​Predefined difficulties

    @Oathkeeper has created and tested predefined difficulty presets for your rules.yml file so you can make LevelledMobs easier or harder within a few seconds.

    By default, the ‘normal’ difficulty is used, which is still based on Minecraft’s ‘hard’ difficulty!! Have your server community’s permission before you crank it up to ‘hard’, LevelledMobs style ;)

## ​Name-tag health indicators

    The LM team worked to improve the name tag system! Not only have we improved the default look of the name tags, we have also added a Health Indicator system so you can see a visual representation of the mob’s health from a distance.

​Other new features

    @stumper66 added custom biome groups to rules.

    @stumper66 added command count to custom-drops debugging.

    @stumper66 added the commands ‘/lm rules reset’, ‘/lm rules help-discord’, and ‘/lm rules help-wiki’.

    @stumper66 added the debug option ‘CREEPER_BLAST_RADIUS’.

    @stumper66 added a new condition to the rules system: ‘max-distance-from-spawn’.

    @stumper66 added the settings option ‘level-mobs-upon-spawn’.

    @stumper66 overhauled the entity name override system with the levels system.

    @stumper66 added the weighted random levelling system option

    @stumper66 added option to use the LM v1 nametag system, although inferior, few have requested the ability to do so. The setting is ‘use-customname-for-mob-nametags’.

    @stumper66 added nbt support to rules

​## Other improvements

    @stumper66 removed the MythicMobs dependency from pom.xml. Not only has this decreased LM’s file size, we now have the ability to release LM versions to the maven repository from JitCI. This may have other side-benefits we are unsure of – we could have added compatibility for MythicMobs 5 in this process although we have not tested this.

    @stumper66 made the LevelInterface an actual interface.

    @stumper66 made creeper-blast-damage now a multiplier.

    @stumper66 made improvements to the YML parsing code which affected a lot of code but should be completely transparent to users.

    @stumper66 updated inbuilt dependency MicroLib for spigot console color compatibility. No more weird symbols in SpigotMC/CraftBukkit server logs! (PaperMC & forks never had this issue.)

    @stumper66 made rules parsing errors show more detailed information, making it easier to diagnose.

    @stumper66 made all rules, customdrops and settings case-insensitive (should be)

## ​Fixes

    @stumper66 fixed weighted-random not working properly.

    @stumper66 fixed the ‘/lm summon’ command not summoning mobs in the correct place. It now summons mobs in front of the player’s direction which they are facing.

    @stumper66 fixed rules chance logic.

    @stumper66 fixed external plugin issues in rules.yml.

    @stumper66 fixed an error whilst setting entity health in some circumstances.

    @stumper66 fixed piglins and piglin_brutes not being in the ‘all_hostile_mobs’ custom group.

    @stumper66 fixed the settings migrator incorrectly migrating the worlds list from LM v2 to LM v3 upgrades.

    @stumper66 fixed the ‘/lm info’ command not showing 1.17 as compatible.

    @stumper66 fixed level 0 mobs getting LevelledMobs name tags.

    @stumper66 fixed bug if the setting sunlight-intensity was utilized and a non-levelled entity such as a baby zombie combusts it would get a nametag with a -1 level

    @stumper66 fixed an exception when applying 0 level to creepers.

**Comment by UltimaOath** [comment]
Might include moving all the config docs to the wiki, which as of this message is about 80% complete (mostly usable now, will be done within the next day).
