### ISSUE TITLE
Request: bStats custom metrics charts

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#251]
Edit this post with any custom metrics that could/should be added to LM's bStats page.

# Probably 👍
* ~~number of rules~~
* ~~has customdrops enabled~~
* ~~uses health indicator~~
* uses player levelling

# Probably 👎
* number of custom drops

**Comment by stumper66** [comment]
Here is what was added:

`maxlevel_used: 1-10, 11-24, 25-50, 51-100, 101-499, 500+
custom_rules_used: 0, 1-2, 3-4, 5+
custom_drops_enabled: Yes/No
health_indicator_enabled: Yes/No
levelling_strategy: Random, Weighted Random, Spawn Distance, Blended, Y-Levelling
autoupdate_checker_enabled: Yes/No
level_mobs_upon_spawn: Yes/No
check_mobs_on_chunk_load: Yes/No
custom-entity-names: 0, 1-3, 4-8, 9-12, 13+
note in most causes it is only checking the default rule
utilizes-nbtdata: Yes/No.  Will only be yes if they have NBTAPI installed and uses either a custom drop or rule with nbtdata`

**Comment by lokka30** [comment]
After release I will try make the metrics appear on the website if they don't already
