### ISSUE TITLE
Add ability for other plugins to disable name tag system affecting certain mobs

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#257]
Can use a PersistentDataContainer value, or even Metadata. Other plugins should be able to set this value on specific mobs, and LM will not change the name tag of mobs which have this value set to `true`, e.g. `LM_NoNametag` or something like that - make sure it matches the format of the other PDC names, I haven't checked those in a long time.

**Comment by lokka30** [comment]
I need to document this before it's solved

**Comment by stumper66** [comment]
@lokka30 
Updated the MobPrelevelEvent with a new function:
https://github.com/lokka30/LevelledMobs/blob/3.2-dev/src/main/java/me/lokka30/levelledmobs/events/MobPreLevelEvent.java#L100

public void setShowLM_Nametag(final boolean doRemove)

**Comment by stumper66** [comment]
Just realized the variable name doesn't make sense, so will update that on the next build

**Comment by lokka30** [comment]
@stumper66 

Please could you rename the method to `public void setShouldShowLevelledNametag(final boolean state)`?

also `state` being my suggested variable name since the method name already implies what the boolean is :)

**Comment by lokka30** [comment]
I need to document this before it is closed

**Comment by lokka30** [comment]
In LM 4 there will be a method in the LevelledMob class that allows plugins to just set a PDC value on the mob.

**Comment by lokka30** [comment]
Need to add the PDC value for this in LM 4 and I also need to add an API method for it

**Comment by lokka30** [comment]
Almost implemented in LM4, just need to make the label systems factor in if a mob has the denied label stamp.

**Comment by lokka30** [comment]
done
