### ISSUE TITLE
Request: Merge debug settings

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#261]
I think debug settings should be merged. e.g. currently there is `debug-misc` and `debug-entity-damage`, I think these should merge into one setting, `debug`. This new setting will be exactly like `debug-misc` however you can include `ENTITY_DAMAGE` (as if it were in the Debug Type enum) to activate debug-entity-damage.

I don't believe the word `misc` is suitable for that setting. When it was first added, it contained minor debug settings, hence 'misc'. Now it encompasses all parts of the debug system apart from entity-damage which could change according to my suggestion above.

No migration should be required if we do change this setting since people shouldn't have debugs left on anyways.

Any thoughts from the team? @stumper66 @UltimaOath Otherwise I will assume it's a great idea and will work on it if I can find the time :)

**Comment by UltimaOath** [comment]
No issues from my side

**Comment by lokka30** [comment]
This will be added to LM4.
