### ISSUE TITLE
Add compatibility for version 2 of the Dangerous Caves plugin

### ISSUE THREAD

**Issue by Snele** [lokka30/LevelledMobs#273]
In the rules.yml config, there are conditions such as:
conditions:
    level-plugins:
      DANGEROUS_CAVES: false
      MYTHIC_MOBS: false
      ELITE_MOBS: false
      ELITE_MOBS_NPCS: false
      ELITE_MOBS_SUPER_MOBS: false
      INFERNAL_MOBS: false
      SHOPKEEPERS: false
And the specified Dangerous Caves plugin is most likely outdated. He has a new version and I would like it to appear there :)
Updated version of Dangerous Caves - https://www.spigotmc.org/resources/dangerous-caves-2-make-your-caves-scary-1-12-2-1-16-5.76212/

**Comment by lokka30** [comment]
> 
> 
> In the rules.yml config, there are conditions such as:
> conditions:
> level-plugins:
> DANGEROUS_CAVES: false
> MYTHIC_MOBS: false
> ELITE_MOBS: false
> ELITE_MOBS_NPCS: false
> ELITE_MOBS_SUPER_MOBS: false
> INFERNAL_MOBS: false
> SHOPKEEPERS: false
> And the specified Dangerous Caves plugin is most likely outdated. He has a new version and I would like it to appear there :)
> Updated version of Dangerous Caves - https://www.spigotmc.org/resources/dangerous-caves-2-make-your-caves-scary-1-12-2-1-16-5.76212/

Hi - thanks for the request! Have you checked if the `DANGEROUS_CAVES` option is also compatible with DC2? I would believe it's quite likely they share the same metadata ID for the mobs that belong to the plugin.
Please let me know. Cheers :+1:

**Comment by Snele** [comment]
I have been working a server with the levelledmobs plugin and Dangerous Caves 2 for a long time. Because of levelledmobs, the mobs of the Dangerous Caves 2 plugin have two different tags that change among themselves. With the characteristics probably also.
So I believe that DANGEROUS_CAVES option is not compatible with DC2 :/

**Comment by lokka30** [comment]
> 
> 
> I have been working a server with the levelledmobs plugin and Dangerous Caves 2 for a long time. Because of levelledmobs, the mobs of the Dangerous Caves 2 plugin have two different tags that change among themselves. With the characteristics probably also.
> So I believe that DANGEROUS_CAVES option is not compatible with DC2 :/

Thanks a lot for the reply - I'm currently very busy but I'll take a look at DC2 compatibility as soon as I get a chance.

**Comment by stumper66** [comment]
@Snele can you please join our discord so we can get more details and discuss the issue above?

**Comment by lokka30** [comment]
Note to self: [see dev response here](https://github.com/imDaniX/Dangerous-Caves-2/issues/50#issuecomment-897747251)

**Comment by lokka30** [comment]
Done, releasing dev build in a tick, but I need to test if it works.

**Comment by lokka30** [comment]
Done in the latest dev build @Snele :+1:

**Comment by Snele** [comment]
So far, everything is fine. If there are any errors, I will report :)
