### ISSUE TITLE
Bug: invincible dead mobs bug is still present

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#277]
See [conversation on Discord](https://discord.com/channels/752310043214479462/760051505067458590/875695786841759786).

MrCrazy reports the same bug we tried to patch in LM 3.1.2: [see photo](https://media.discordapp.net/attachments/760051505067458590/875695783725371402/2021-08-13_20.53.51.png?width=1289&height=683)

**Comment by lokka30** [comment]
This user's server has been the forefront of many unusual LM bugs.

**Comment by UltimaOath** [comment]
This user refuses to test their other plugins to verify no others are causing issue. The ones he reports are not repeatable in a local test environment using identical rules/settings files.
