### ISSUE TITLE
Slime size conditions

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#279]
Add a option for us to check if the SLIME or MAGMA CUBE is normal, medium or small size as requirement to applying levels to them. // Apply it when it gets killed and shrinked)?

https://discord.com/channels/752310043214479462/829238692161781770/875688452346245141

**Comment by lokka30** [comment]
@stumper66 and/or @UltimaOath - any thoughts on this suggestion?

**Comment by UltimaOath** [comment]
I like the idea, idk the feasibility of using NBT-API as a condition check, to check the nbt data of a spawned entity for the particular nbt data in a easy to replicate method. Allowing us to check for NBT data on the entity will allow this to work, as the size is stored in this way, but it could also open the door to other modifications that are nbt check based.

**Comment by lokka30** [comment]
> I like the idea, idk the feasibility of using NBT-API as a condition check, to check the nbt data of a spawned entity for the particular nbt data in a easy to replicate method. Allowing us to check for NBT data on the entity will allow this to work, as the size is stored in this way, but it could also open the door to other modifications that are nbt check based.

I like your thinking. I'll create a separate issue for 'conditions that can utilise NBT API'.

**Comment by stumper66** [comment]
Spigot can check slime size.  No need for 3rd party tools.

**Comment by lokka30** [comment]
> 
> 
> Spigot can check slime size. No need for 3rd party tools.

Okay. I'll assign this to LM 3.4

**Comment by lokka30** [comment]
Added to rule brainstorming file. Will close this
