### ISSUE TITLE
Partial re-code and re-structure.

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#282]
LevelledMobs' classes are becoming difficult for me and other developers to use. I want to clean up the plugin almost the completely. This will involve creating new classes, possibly removing existing ones, possibly breaking existing integrations with other plugins.

A **partial** re-code will be a must.

This will be a major change to LM's code, it could even go into LevelledMobs 4 territory.

Any thoughts on this?

**Comment by lokka30** [comment]
Tagging team. @UltimaOath @stumper66 Respond if you want, whenever you want :+1:

**Comment by UltimaOath** [comment]
#243

**Comment by lokka30** [comment]
> #243

Just in case you thought this was a duplicate: this issue encompasses the *entire* plugin, not just the levelling systems. #243 must be completed prior to this of course. Or even, it could be done at the same time - which would make a lot of sense honestly.

**Comment by lokka30** [comment]
This is being undertaken in LevelledMobs v4.0, which is currently in development (see `4.0-dev` branch). However, it is not a *partial* re-code, but a **full** re-code, to unlock all of the goodness we can.

**Comment by lokka30** [comment]
In progress for LM 4.
