### ISSUE TITLE
Assignable PDC values in the rules system

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#283]
Random idea popped in my head, unsure if it is a good one or not. What if rules can interact each other by setting PersistentDataContainer (PDC) values on mobs? E.g., one rule assigns a pdc value, another rule has a condition that the pdc value must exist, maybe even with a specific value.

**Comment by UltimaOath** [comment]
I'm liking the concept overall; my personal opinion might be to craft a specific field in the PCD which can be influenced by the admin via an apply-setting. The user crafts a PCD line item, adds it to the entity through apply-settings, and now we can search for those PCD lines via a condition check. TLDR adding ability for users to add one or more line items to the pcd which would be little more than 'category' markers of some kind.

**Comment by lokka30** [comment]
Perhaps this PDC namespaced key should be a List of strings so a mob can be given multiple values within it.

**Comment by lokka30** [comment]
This will be added to LM v4.0
it has been added to the actions brainstorming file
