### ISSUE TITLE
Allow checking of perms in rules

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#285]
@UltimaOath said:
An idea in the future as one of those larger updates might be to allow owners to construct their own permission nodes which can then be checked via a condition. For example, craft a node called lm.perm.vipdrops and give that to a few VIP players. Then I have a custom rule condition checking along the lines of player-permission: ['vipdrops'] which, when an entity dies at the hands of a vip player, will activate the custom rule. Allowing the user control over making the perms allows them to make any use of them as they desire and it would resolve a couple similar permission based requests. I also believe this could be extended to the customdrops system as well, where they require a permission for the special drops to happen even if it's enabled by default. This could be useful for establishing that new players get the vanilla loot but players with history get the custom drops permission, and could have tiers of permissions with tiers of different items, entities, rules etc.

@lokka30 replied:
I think instead of forcing the lm.perm prefix, no prefix at all - e.g. if you want a rule to check if players have the perm essentials.help then it's possible :)

**Comment by stumper66** [comment]
This was partially implemented in 3.2.0 b524:
```
added player permissions rule condition and custom drop permissions (#237)
```

**Comment by stumper66** [comment]
Mentioning #237

**Comment by lokka30** [comment]
This will be added in v4.0
