### ISSUE TITLE
Create addon that adds a PAPI placeholder 'distance to nearest home', usable in Player Levelling

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#292]
See [this](https://www.spigotmc.org/threads/levelledmobs-for-1-16-x-1-17-x.412953/page-16#post-4253495) discussion.

If the player has no home set in the world they are in, it will use the world's spawnpoint.

**Comment by stumper66** [comment]
added 3 new variables listed below.
These require EssentialsX to be installed:
```
%home_distance%
%home_distance_with_bed%
```
This one has no 3rd party dependencies:
```
%bed_distance%
```

**Comment by UltimaOath** [comment]
Tested and confirmed mostly working in b578  
Requires fix for debug messages and accurately applying nether portal shift within all three variables (specifically the bed parts lack it).

**Comment by UltimaOath** [comment]
Minor debug updates, potential update if player goes from nether to overworld via portal if their home is set in Nether. Currently it uses world spawn, suggested it use the nether portal coordinates instead in similar way we use when tracking a player from overworld into nether.
