### ISSUE TITLE
SimplePets mobs should not be levelled by default

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#297]
These mobs should not be levelled by default

https://www.spigotmc.org/resources/simplepets.14124/

Reported by SpigotMC user `Tomitytom` in PMs

Whilst working on this I should also consider any other plugins alike

**Comment by stumper66** [comment]
Added to 3.2.0 b520.
However SimplePets appears to remove any PDC keys so it is best to left them unlevelled otherwise they will get relevelled every 5 seconds.
