### ISSUE TITLE
Add `NametagVisibilityMode.MARKED`

### ISSUE THREAD

**Issue by UltimaOath** [lokka30/LevelledMobs#301]
As part of the new 3.2 nametag system, a feature called MARKED.

Under this scenario alone, nametags would be visible similar to MELEE effect. The Player could, within a configured distance AND/OR with a configured item in hand (suggestion: spyglass), the Player would use a configured button click to 'mark' the entity, thus keeping it's nametag visible to the player as if ALWAYS_ON was enabled. The tag would not disappear until entity is 'unmarked' by repeating the process, X time elapses, or left on until entity dies/reload/restart is performed.

**Comment by UltimaOath** [comment]
Did a bit of research, found this which might aid in endevour:  
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerInteractEntityEvent.html#getRightClicked()

**Comment by UltimaOath** [comment]
#327 \<- this mechanic could also work here; target can only be marked if within X distance.

**Comment by stumper66** [comment]
It's looking like this might not be possible.
Currently there is no event fired when using a spyglass so we'd have no way of knowing if it's even in use.
Second it would be extremely difficult to tell what mob is being looked at and.
Third, you can't click left or right-mouse button or type in any commands while looking thru the spyglass.

**Comment by UltimaOath** [comment]
I only suggested the spyglass as a novel way of implementation; I suggested to use the `getRightClicked` event, where a player right clicks an entity with their mouse, and if this is able to be registered mark the entity to have nametag displayed.

**Comment by stumper66** [comment]
It seemed to make the most sense to me to tag enemies from afar, otherwise you have to be within melee range to click on them.
Is that the desired behavior?
I assume this will be used for hostile mobs.

**Comment by UltimaOath** [comment]
Yes. Imagine the current `TRACKING` mechanism, where LoS is required, but instead of it automatically activating, the player must right click on the entity within X distance (the distance being the distance mechanic you suggested in #327 ), and then that entity is visible to the player who right clicked it for Y time, where Y is an extended amount of time that a marked entity nametag would remain visible (would prob. need a config timer for it).  
  
I think this would work for entities from afar; I assumed `getRightClicked` didn't have a distance component. I know there is a way to identify entities just by looking at them regardless of distance, because the debug menu F3 reveals that information.

**Comment by UltimaOath** [comment]
Yes. Imagine the current `TRACKING` mechanism, where LoS is required, but instead of it automatically activating, the player must right click on the entity within X distance (the distance being the distance mechanic you suggested in #327 ), and then that entity is visible to the player who right clicked it for Y time, where Y is an extended amount of time that a marked entity nametag would remain visible (would prob. need a config timer for it).  
  
I think this would work for entities from afar; I assumed `getRightClicked` didn't have a distance component. I know there is a way to identify entities just by looking at them regardless of distance, because the debug menu F3 reveals that information.

**Comment by UltimaOath** [comment]
On a separate not regarding the Spyglass suggestion, there are three achievements regarding looking at specific entities through the spyglass. This tells me that there is a way to both register a player has a spyglass up and open and to identify whatever entity it's looking at. I'll have to do more research into it though.

**Comment by lokka30** [comment]
We can use a repeating task whilst a player is holding a spyglass (can't tell if they're using it or not) that marks entities which their crosshair is exactly on. Hope this is possible. what'cha think

**Comment by lokka30** [comment]
Will have to drop the spyglass part of the suggestion, it's unfeasible. Marking entities is done by damage/right-click only.

**Comment by lokka30** [comment]
Added to brainstorming actions file
