### ISSUE TITLE
Stat Tradeoff as an additional stat modifying scheme for levellable mobs

### ISSUE THREAD

**Issue by jwevans1989** [lokka30/LevelledMobs#306]
Currently, there are two possible ways (I believe) to modify mob stats without having to use custom rules. One is to positively scale stats according to the mob level (stats increase as mob level increases), and the other is to negatively scale them in a "stat tradeoff" scheme (a mob gets an insane damage boost, but may have drastically lower speed or health as a tradeoff). 

The way to implement stat tradeoffs is to use negative values in the stat modifiers in place of positive values. However, this is an unintended feature, and may cause problems down the road.

**Solution**

**Use a "stat-decrease" subcondition to multipliers.** This would either come in the form of:

- a modal list (`allowed-list` or `excluded-list`) that would define which stats will be negatively scaled, or will not be negatively scaled, respectively; or
- a boolean `stat-decrease` subcondition beneath each stat modifier.

Combined with chances and entity name overrides in custom rules, this can allow for a wider variety of mobs. For example, there can be normal zombies, "tank" zombies with a large health pool and high damage, but slow attack speed and movement speed, and "rusher" zombies with low health, moderate damage, and really fast attack speed and movement speed.

* I feel like I'm missing something. Might add more details if I remember them.

**Comment by lokka30** [comment]
This is possible in LM v4.0 via using custom attribute formulas.
