### ISSUE TITLE
Add a placeholder that updates when you look at an enemy

### ISSUE THREAD

**Issue by Veggum0** [lokka30/LevelledMobs#318]
I'm trying to use ActionHealth and LevelledMobs together and have the mobs name / level displayed on ActionHealth so players can see the level of mobs easily from a distance. (Sometimes nametags can be too small / hidden to read easily.) and it works great using PlaceholderAPI and **%levelledmobs_displayname%** however it only updates when a mob was killed / has killed a player. It would be really nice if yall could add a placeholder thats set to update automatically and not only when mobs are interacted with otherwise players will look at a mob and see the incorrect info on screen. 

I understand this might be more resource intensive than not having it, however you could just add a toggle and put a note next to it saying its more resource intensive and have it off by default.

Thank you for your time and amazing plugin, been using it since early 1.15 and I'm amazed with how many features yall have added that I was wanting already. As of now this is the only thing that's missing for me personally. :) <3
[
Screenshot of what I'm doing](https://cdn.discordapp.com/attachments/760051505067458590/905569826926366730/2021-11-03_16_30_33-Microsoft_Store.png)

**Comment by lokka30** [comment]
> 
> 
> I'm trying to use ActionHealth and LevelledMobs together and have the mobs name / level displayed on ActionHealth so players can see the level of mobs easily from a distance. (Sometimes nametags can be too small / hidden to read easily.) and it works great using PlaceholderAPI and **%levelledmobs_displayname%** however it only updates when a mob was killed / has killed a player. It would be really nice if yall could add a placeholder thats set to update automatically and not only when mobs are interacted with otherwise players will look at a mob and see the incorrect info on screen.
> 
> I understand this might be more resource intensive than not having it, however you could just add a toggle and put a note next to it saying its more resource intensive and have it off by default.
> 
> Thank you for your time and amazing plugin, been using it since early 1.15 and I'm amazed with how many features yall have added that I was wanting already. As of now this is the only thing that's missing for me personally. :) <3 [ Screenshot of what I'm doing](https://cdn.discordapp.com/attachments/760051505067458590/905569826926366730/2021-11-03_16_30_33-Microsoft_Store.png)

I like your idea, and I'm glad to hear you've been with us for so long!
I'm not certain on what you are looking for though. Please could you elaborate further? For action health, wouldn't something like `%levelledmobs_last_hit%` be more suitable?

**Comment by Veggum0** [comment]
> > I'm trying to use ActionHealth and LevelledMobs together and have the mobs name / level displayed on ActionHealth so players can see the level of mobs easily from a distance. (Sometimes nametags can be too small / hidden to read easily.) and it works great using PlaceholderAPI and **%levelledmobs_displayname%** however it only updates when a mob was killed / has killed a player. It would be really nice if yall could add a placeholder thats set to update automatically and not only when mobs are interacted with otherwise players will look at a mob and see the incorrect info on screen.
> > I understand this might be more resource intensive than not having it, however you could just add a toggle and put a note next to it saying its more resource intensive and have it off by default.
> > Thank you for your time and amazing plugin, been using it since early 1.15 and I'm amazed with how many features yall have added that I was wanting already. As of now this is the only thing that's missing for me personally. :) <3 [ Screenshot of what I'm doing](https://cdn.discordapp.com/attachments/760051505067458590/905569826926366730/2021-11-03_16_30_33-Microsoft_Store.png)
> 
> I like your idea, and I'm glad to hear you've been with us for so long! I'm not certain on what you are looking for though. Please could you elaborate further? For action health, wouldn't something like `%levelledmobs_last_hit%` be more suitable?

While in theory that would work okay in combat, when you're walking around and look at a mob in the distance it will display the last mob you hit's info / name alongside the hp of the mob you're actually looking at with actionhealth. I specifically need a placeholder that will update the entire display name when a mob is looked at so actionhealth can take that info and display it on screen so you get the correct info about the mob you're looking at.

**Comment by lokka30** [comment]
> 
> 
> > > I'm trying to use ActionHealth and LevelledMobs together and have the mobs name / level displayed on ActionHealth so players can see the level of mobs easily from a distance. (Sometimes nametags can be too small / hidden to read easily.) and it works great using PlaceholderAPI and **%levelledmobs_displayname%** however it only updates when a mob was killed / has killed a player. It would be really nice if yall could add a placeholder thats set to update automatically and not only when mobs are interacted with otherwise players will look at a mob and see the incorrect info on screen.
> > > I understand this might be more resource intensive than not having it, however you could just add a toggle and put a note next to it saying its more resource intensive and have it off by default.
> > > Thank you for your time and amazing plugin, been using it since early 1.15 and I'm amazed with how many features yall have added that I was wanting already. As of now this is the only thing that's missing for me personally. :) <3 [ Screenshot of what I'm doing](https://cdn.discordapp.com/attachments/760051505067458590/905569826926366730/2021-11-03_16_30_33-Microsoft_Store.png)
> > 
> > 
> > I like your idea, and I'm glad to hear you've been with us for so long! I'm not certain on what you are looking for though. Please could you elaborate further? For action health, wouldn't something like `%levelledmobs_last_hit%` be more suitable?
> 
> While in theory that would work okay in combat, when you're walking around and look at a mob in the distance it will display the last mob you hit's info / name alongside the hp of the mob you're actually looking at with actionhealth. If you look at the screenshot in the original post it shows on the hud i'm staring at a lvl 13 zombie with 0 hp, while in reality im looking at a lvl 6 zombie with 20 hp. I specifically need a placeholder that will update the entire display name when a mob is looked at so actionhealth can take that info and display it on screen so you get the correct info about the mob you're looking at.

Ah, I see now. I think we may as well add both placeholders in. Thanks for the explanation.

**Comment by Veggum0** [comment]
> > > > I'm trying to use ActionHealth and LevelledMobs together and have the mobs name / level displayed on ActionHealth so players can see the level of mobs easily from a distance. (Sometimes nametags can be too small / hidden to read easily.) and it works great using PlaceholderAPI and **%levelledmobs_displayname%** however it only updates when a mob was killed / has killed a player. It would be really nice if yall could add a placeholder thats set to update automatically and not only when mobs are interacted with otherwise players will look at a mob and see the incorrect info on screen.
> > > > I understand this might be more resource intensive than not having it, however you could just add a toggle and put a note next to it saying its more resource intensive and have it off by default.
> > > > Thank you for your time and amazing plugin, been using it since early 1.15 and I'm amazed with how many features yall have added that I was wanting already. As of now this is the only thing that's missing for me personally. :) <3 [ Screenshot of what I'm doing](https://cdn.discordapp.com/attachments/760051505067458590/905569826926366730/2021-11-03_16_30_33-Microsoft_Store.png)
> > > 
> > > 
> > > I like your idea, and I'm glad to hear you've been with us for so long! I'm not certain on what you are looking for though. Please could you elaborate further? For action health, wouldn't something like `%levelledmobs_last_hit%` be more suitable?
> > 
> > 
> > While in theory that would work okay in combat, when you're walking around and look at a mob in the distance it will display the last mob you hit's info / name alongside the hp of the mob you're actually looking at with actionhealth. If you look at the screenshot in the original post it shows on the hud i'm staring at a lvl 13 zombie with 0 hp, while in reality im looking at a lvl 6 zombie with 20 hp. I specifically need a placeholder that will update the entire display name when a mob is looked at so actionhealth can take that info and display it on screen so you get the correct info about the mob you're looking at.
> 
> Ah, I see now. I think we may as well add both placeholders in. Thanks for the explanation.

Thank you <3 :)

**Comment by UltimaOath** [comment]
`%levelledmobs_mob-target%` used in unreleased 3.3.X ; still needs bugfix/changes

May implement #212 as side effect of placeholder and `nametag_placeholder:` suggestion. NOT FINAL! JUST FOR NOTES SAKE!

**Comment by Veggum0** [comment]
> `%levelledmobs_mob-target%` used in unreleased 3.3.X ; still needs bugfix/changes
> 
> May implement #212 as side effect of needing to handle non-levelled entities via placeholder and `nametag_placeholder:` suggestion. NOT FINAL! JUST FOR NOTES SAKE!
> 
> Also need to create config for the distance the placeholder can search, or if this is even necessary in terms of resource (whether maxing out the distance is significant difference resource wise versus a more conservative number).
> 
> ![example from PenalBuffalo of it working](https://user-images.githubusercontent.com/19399136/141211748-ae98411b-dfac-45d9-9a4c-ce8663966468.png)

Thank you so much for your work! <3 I can't wait to try it out. As for the distance I'm going to be using the placeholder in ActionHealth and in that plugin I have the distance set to 20 blocks and I personally feel like thats a pretty good distance for the default value. It would certainly be nice to have the ability to change the value in levelledmobs itself though.

**Comment by stumper66** [comment]
Added to 3.3.0 b561

**Comment by UltimaOath** [comment]
Tested and confirmed working in b561  
Made suggestion of implementing #212 since we already use tags for the non-levelled placeholder.
