### ISSUE TITLE
ranged mobs increased damage

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#32]
probably done by listening to projectilehitevent or something and checking the shooter if it is levellable get its level

**Comment by Eyrian2010** [comment]
I'd try it via EntityDamageByEntityEvent, check if damager is instance of projectile. Afterwards check if shooter of said projectile is a living, levellable entity, and set the damage via 'setDamage()' to get it handled correctly.

Cheers,
Eyrian

**Comment by lokka30** [comment]
added in upcoming release
