### ISSUE TITLE
NameTag

### ISSUE THREAD

**Issue by PitaChleba** [lokka30/LevelledMobs#321]
Hey, i want to ask, I don't see nametags above the mobs. How can I set it up?
Thx for help 0:)

**Comment by UltimaOath** [comment]
Do you have protocollib installed it is a required dependency for the name tags to be visible

**Comment by PitaChleba** [comment]
Oh thanks, I don't have it. I'm going to fix it. And one question, when I don't want the player levelling system, how can I remove it?

**Comment by UltimaOath** [comment]
By default it is not enabled so unless you enabled it it shouldn't be on.

**Comment by stumper66** [comment]
@PitaChleba if you have any questions or problems it is recommended to join our discord.
We can show you how to enable many cool features of LevelledMobs.
https://www.discord.io/arcaneplugins
