### ISSUE TITLE
Multiply damage dealt to a levelled mob by its `DamageCause`

### ISSUE THREAD

**Issue by UltimaOath** [lokka30/LevelledMobs#328]
```yaml
  apply-settings:
    drowning-intensity: 15
```

Functions similar to how we use `sunlight-intensity:`, and for the same reason I hadn't thought of until now: high level entities staying alive because of their health underwater.

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/EntityAirChangeEvent.html
I suggest checking when this event occurs then applying the extra damage, or if there's a better/more accurate way.

**Comment by lokka30** [comment]
Perhaps we can offer damage amplification for other 'damage reasons' than just drowning

**Comment by lokka30** [comment]
Same code, more configurable

**Comment by UltimaOath** [comment]
I'm happy to go this route if it's easy enough to implement ; if we do we will want to remove the `sunlight-intensity:` config option and replace it with whichever new system we're going to use.

**Comment by lokka30** [comment]
we can migrate that option to whatever new system comes

**Comment by UltimaOath** [comment]
#302 So I remembered that I had already made a buff/nerf system for the `EntityDamageEvent.DamageCause` , however looking at how we handle `sunlight-intensity:` which is the sister setting to this suggestion, it is handled under `event.entity.EntityCombustByBlockEvent` which takes me down to `event.entity.EntityEvent` . This list of events to search for are so niche that I doubt it would be useful.   
  
Upon reflection, I think simply adding the original suggestion of a `drowning-intensity:` next to `sunlight-intensity:` would resolve the specific issues (in hindsight maybe even a `lava-intensity:` setting for similar reasons). And then in the future when/if we implement #302 for the regular damage events.

**Comment by lokka30** [comment]
Perhaps we could 'expand' the [list of damage causes](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html), e.g. 'sunlight' being a new one.

**Comment by lokka30** [comment]
Nevermind, #302 is perfect, and will solve this issue :)
