### ISSUE TITLE
Make Custom Drops probability decrease when farming mobs in a single chunk

### ISSUE THREAD

**Issue by jeffry1829** [lokka30/LevelledMobs#338]
**Is your feature request related to a problem? Please describe.**
Player can use mob farms to farm drops from high level mobs easily.

**Describe the solution you'd like**
The plugin can count the mobs killed by player within a chunk in a given period.
We can set variables: threshold, cool_down_time
The final drop probability=probability*(threshold-number of killed mobs within the cool_down_time)/threshold

Thank you!

**Comment by lokka30** [comment]
This sounds like a nice idea, thanks for the suggestion!

**Comment by UltimaOath** [comment]
This feature has been added as of b625
