### ISSUE TITLE
Make player levelling implement a configurable default strategy for a temporary level

### ISSUE THREAD

**Issue by UltimaOath** [lokka30/LevelledMobs#346]
https://discord.com/channels/752310043214479462/757933745620779033/919485920451903490

Incase it's forgotten

> I just want to point out for complete clarification: my proposed idea would mean that by having the difficulty and World selected in the presets, and then having player levelling enabled, would work just the same as if I had spawn distance or any other strategy enabled. If I have player levelling enabled, nothing would change from the players point of view, since they should only be interacting with entities which had updated due to proximity. The part that would change, which players wouldn't notice unless they sat and watched entities spawn in the far distance, is that instead of relying on another strategy to process the level, and then for Player levelling to change the level, it would be a singular application of the base vanilla level one across all spawned entities that would have fallen under player levelling assuming no player was nearby to set the player levelling from the getgo.

**Comment by lokka30** [comment]
@UltimaOath I can't really understand what the quote says but it does ring a bell. Is this about having a default strategy determine the level for mobs until player levelling can sweep it up?

**Comment by lokka30** [comment]
Added to brainstorming action file
