### ISSUE TITLE
Non-levelled slimes/magma cubes, when killed, split into levelled counterparts

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#354]
The intended behaviour is that the split magma cubes and slimes remain non-levelled.

**Comment by UltimaOath** [comment]
Unable to replicate on latest LM/Paper, LM/Spigot build for 1.18.1

**Comment by UltimaOath** [comment]
UPDATE:  
  
Bug confirmed; any entity which transforms, including slimes, magma cubes, zombies -> drowned, etc. which have been spawned via the allowed-spawn-reason condition will not inherit the condition upon transforming. This can allow entities to become levelled when they were not intended to be so, or vice versa.  
  
Current solution is to allow `level-inheritance:` to handle these exceptions. Update coming soon!

**Comment by lokka30** [comment]
solved in b602
