### ISSUE TITLE
LM 3.1 custom drops don't stack with 3.3's

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#361]
See private channel `#ticket-290`.

**Comment by stumper66** [comment]
This is caused by LM 3.3 using Paper's API to create custom names using Adventure Components.  Pre 3.3 used Spigot API which uses basic strings for text.
Example, here is a basic item with a custom name in 3.1:
```
{display: {Name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"Carne putrefacta"}],"text":""}'}}

```
and the same item created in 3.3:
```
tag: {display: {Name: '{"text":"§cCarne putrefacta"}'}}
```

**Comment by stumper66** [comment]
This is unlikely to be resolved. The best solution is to rid any items created pre 3.3.

**Comment by UltimaOath** [comment]
While the issue itself is unlikely to be resolved, we have incorporated b609 `use-adventure` which may mitigate the issue for future releases.
