### ISSUE TITLE
Scalling for mobs is kinda bad and I need some help making it fit my server better

### ISSUE THREAD

**Issue by Eris7090** [lokka30/LevelledMobs#384]
On my server I'm using mcMMO and set the player leveling to mcmmo level but without random weighted on leveled mobs don't spawn which is fine I'll just keep it on as well as player leveling. but here's the issue. mcmmo scales pretty high, I have it set to go to 100, and leveled mobs doesn't scale well at all. The average challenge is way too easy and caps out way too early but the advanced challenge is why too hard early on and it caps out at 50. I tried adding more tiers to player leveling but then mobs didn't have levels at all. I couldn't find documentation on this specific subject but maybe there is and you can link it to me. I also tried to join your discord server but I have to verify with a phone number and I'm not giving discord my phone number.

**Comment by Eris7090** [comment]
I also tried to message on spigot and it was marked as spam or inappropriate. Above is exactly what I had typed in spigot message.

**Comment by Eris7090** [comment]
`#                    _                   _ _          _ __  __       _
#                   | |    _____   _____| | | ___  __| |  \/  | ___ | |__  ___
#                   | |   / _ \ \ / / _ \ | |/ _ \/ _` | |\/| |/ _ \| '_ \/ __|
#                   | |__|  __/\ V /  __/ | |  __/ (_| | |  | | (_) | |_) \__ \
#                   |_____\___| \_/ \___|_|_|\___|\__,_|_|  |_|\___/|_.__/|___/
#                             The Ultimate RPG Levelled Mobs Solution
#
# --------------------------------------------------------------------------------------------LM3
# +                                      ++                                                  +LM3
# +  Main Developers                     ++  Need support documentation?                     +LM3
# +    lokka30                           ++    https://github.com/lokka30/LevelledMobs/wiki  +LM3
# +      Author and developer            ++                                                  +LM3
# +      https://ko-fi.com/lokka30       ++  ArcanePlugins Support Discord                   +LM3
# +                                      ++    https://discord.gg/RQ8M4A5                    +LM3
# +                                      ++                                                  +LM3
# +    stumper66                         ++  Special thanks:                                 +LM3
# +      Developer since v2              ++    ArcanePlugins developers and testers!         +LM3
# +      https://ko-fi.com/penalbuffalo  ++    Donators, patrons, and other supporters!      +LM3
# +                                      ++    SpigotMC, PaperMC, ProtocolLib, NBT-API,      +LM3
# +                                      ++    PlaceholderAPI, and bStats!                   +LM3
# +    UltimaOath                        ++                                                  +LM3
# +      Docs and configs since v2       ++  Other Contributors:                             +LM3
# +                                      ++    Eyrian, iCodinqs, deiphiz, CoolBoy, Esophose, +LM3
# +                                      ++    7smile7, Hugo5551, konsolas, Shevchik,        +LM3
# +                                      ++    limzikiki, and Zombie_Striker                 +LM3
# +                                      ++                                                  +LM3
# --------------------------------------------------------------------------------------------LM3
#                                     _____     _
#                                    | __  |_ _| |___ ___
#                                    |    -| | | | -_|_ -|
#                                    |__|__|___|_|___|___|
#
# +-------------------------------------------------------------------------------------------LM3
# +                                                                                          +LM3
# +   Section 01 - Custom Entity and Biome Groups                                            +LM3
# +                                                                                          +LM3
# +-------------------------------------------------------------------------------------------LM3
mob-groups:
  commons:
    - ZOMBIE
    - SKELETON
    - CREEPER
  farm:
    - CHICKEN
    - COW
    - SHEEP
    - PIG


biome-groups:
  taigas:
    - TAIGA
    - TAIGA_MOUNTAINS
    - SNOWY_TUNDRA
    - SNOWY_TAIGA
    - SNOWY_TAIGA_HILLS
    - GIANT_TREE_TAIGA
    - GIANT_SPRUCE_TAIGA
    - GIANT_SPRUCE_TAIGA_HILLS
    - GIANT_TREE_TAIGA_HILLS
    - SNOWY_TAIGA_MOUNTAINS
  flowers:
    - FLOWER_FOREST
    - SUNFLOWER_PLAINS

# +-------------------------------------------------------------------------------------------LM3
# +                                                                                          +LM3
# +   Section 02 - Presets                                                                   +LM3
# +                                                                                          +LM3
# +   This section comes prebuilt with several sets of PRESETS to use with LevelledMobs!     +LM3
# +   Out-of-the-box most of these PRESETS are not enabled, and are only here to both        +LM3
# +   demonstrate the system and allow you to quickly change or use many of the most         +LM3
# +   popular features LevelledMobs has to offer! If you need help understanding PRESETS,    +LM3
# +   read the official LevelledMobs Wiki!                                                   +LM3
# +   https://github.com/lokka30/LevelledMobs/wiki/Documentation---rules.yml#presets         +LM3
# +                                                                                          +LM3
# +-------------------------------------------------------------------------------------------LM3
presets:
  spawn_Levelling:
#   This Strategy Preset controls the Spawn-Distance-Levelling system.
    name: 'LVLling Strategy - Distance-From-Spawn'
    strategies:
      distance-from-spawn:
        increase-level-distance: 150
        start-distance: 250
        spawn-location:
          x: default
          z: default

  blended_Levelling:
#   This Strategy Preset controls the Blended-Levelling sub-system to Spawn-Distance-Levelling.
    name: 'LVLling Strategy - Blended-Levelling'
    strategies:
      distance-from-spawn:
        blended-levelling:
          enabled: true
          transition-y-height: 62
          lvl-multiplier: 0.05
          multiplier-period: 10
          scale-downward: true

  random_Levelling:
#   This Strategy Preset controls the Random-Levelling system.
    name: 'LVLling Strategy - Random'
    strategies:
      random: true
      lower-mob-level-bias-factor: 5

  weighted_random_basic:
    #   This Strategy Preset controls Weighted Random Bias.
    name: 'LVLling Strategy - Weighted Random Bias BASIC Challenge'
    strategies:
      weighted-random:
        1-2: 5
        3-4: 4
        5-6: 3
        7-8: 2
        9-10: 1

  weighted_random_average:
    #   This Strategy Preset controls Weighted Random Bias.
    name: 'LVLling Strategy - Weighted Random Bias AVERAGE Challenge'
    strategies:
      weighted-random:
        1-5: 5
        6-10: 4
        11-15: 3
        16-20: 2
        21-25: 1

  weighted_random_advanced:
#   This Strategy Preset controls Weighted Random Bias.
    name: 'LVLling Strategy - Weighted Random Bias ADVANCED Challenge'
    strategies:
      weighted-random:
        1-9: 5
        10-19: 4
        20-29: 3
        30-39: 2
        40-50: 1
        
  weighted_random_extreme:
#   This Strategy Preset controls Weighted Random Bias.
    name: 'LVLling Strategy - Weighted Random Bias EXTREME Challenge'
    strategies:
      weighted-random:
        1-19: 5
        20-39: 4
        40-59: 3
        60-79: 2
        80-100: 1

  player_Levelling:
#   This Strategy Preset controls the player-stat based levelling system.
    name: 'LVLling Strategy - Player Based AVERAGE CHALLENGE'
    strategies:
      player-levelling:
        match-level: false
        use-player-max-level: false
        decrease-level: true
        player-level-scale: 1.0
        level-cap: 50
        tiers:
          1-20: 1-10
          20-30: 11-15
          31-50: 16-20
	  51-60: 26-30
	  61-80: 31-35
	  81-90: 36-40
	  91-100: 41-50
        variable: '%mcmmo_power_level%'

  apply_LevellingVariance:
#   This Strategy Preset controls the random level variance applied.
    name: 'LVLling Strategy - Apply Variance'
    strategies:
      max-random-variance: 2

  ycoord_Levelling:
#   This Strategy Preset controls Y-Coordinate-Levelling.
    name: 'LVLling Strategy - Y-LVLling'
    strategies:
      y-coordinate:
        start: 100
        end: 20
        period: 0

  allowed_worlds:
#   This controls the allowed worlds to apply levels too.
    name: 'Excluded Worldlist'
    conditions:
      worlds:
#        allowed-list: ['*']
        excluded-list: ['world_the_end']

  basic_challenge:
    name: 'Basic-Challenge Multipliers'
    apply-settings:
      minLevel: 1
      maxLevel: 10
      multipliers:
        max-health: 2.5
        attack-damage: 1.0
        ranged-attack-damage: 1.0
        item-drop: 3
        xp-drop: 5

      tiered-coloring:
        1-2: '&#22E76B' #Green
        3-4: '&#528CFF' #Blue
        5-6: '&#FFCD56' #Yellow
        7-8: '&#F2003D' #Red
        9-10: '&#B447FF' #Purple
        default: '&#FFFFFF' #White
      health-indicator:
        scale: 2
        max: 5
        merge: true

  average_challenge:
    name: 'Average-Challenge Multipliers'
    apply-settings:
      minLevel: 1
      maxLevel: 25
      multipliers:
        max-health: 5.0
        movement-speed: 0.15
        attack-damage: 2.25
        ranged-attack-damage: 2.25
        creeper-blast-damage: 0.75
        item-drop: 3
        xp-drop: 5
#       Special Multipliers (0.0 Min - 1.0 Max)
        armor-bonus: 0.2
        armor-toughness: 0.15

      tiered-coloring:
        1-5: '&#22E76B' #Green
        6-10: '&#528CFF' #Blue
        11-15: '&#FFCD56' #Yellow
        16-20: '&#F2003D' #Red
        21-25: '&#B447FF' #Purple
        default: '&#FFFFFF' #White
      health-indicator:
        scale: 4
        max: 5
        merge: true

  advanced_challenge:
    name: 'Advanced-Challenge Multipliers'
    apply-settings:
      minLevel: 1
      maxLevel: 50
      multipliers:
        max-health: 8.0
        movement-speed: 0.35
        attack-damage: 3.5
        ranged-attack-damage: 2.75
        creeper-blast-damage: 1.75
        follow-range: 0.25
        item-drop: 3
        xp-drop: 5
#       Special Multipliers (0.0 Min - 1.0 Max)
        armor-bonus: 0.3
        armor-toughness: 0.3
        attack-knockback: 0.5
        knockback-resistance: 0.5

      tiered-coloring:
        1-9: '&#22E76B' #Green
        10-19: '&#528CFF' #Blue
        20-29: '&#FFCD56' #Yellow
        30-39: '&#F2003D' #Red
        40-50: '&#B447FF' #Purple
        default: '&#FFFFFF' #White
      health-indicator:
        scale: 8
        max: 5
        merge: true

  extreme_challenge:
    name: 'Extreme-Challenge Multipliers'
    apply-settings:
      minLevel: 1
      maxLevel: 100
      multipliers:
        max-health: 15.0
        movement-speed: 1.0
        attack-damage: 5.0
        ranged-attack-damage: 4.0
        creeper-blast-damage: 2.5
        follow-range: 0.5
        item-drop: 3
        xp-drop: 5
#       Special Multipliers (0.0 Min - 1.0 Max)
        armor-bonus: 0.5
        armor-toughness: 0.5
        attack-knockback: 0.5
        knockback-resistance: 0.5
        zombie-spawn-reinforcements: 0.15

      tiered-coloring:
        1-19: '&#22E76B' #Green
        20-39: '&#528CFF' #Blue
        40-59: '&#FFCD56' #Yellow
        60-79: '&#F2003D' #Red
        80-100: '&#B447FF' #Purple
        default: '&#FFFFFF' #White
      health-indicator:
        scale: 16
        max: 5
        merge: true

  nametag_using_indicator:
#   This controls the nametag, where the health is displayed using %health-indicator%
    name: 'Nametag - Health Indicator'
    apply-settings:
      nametag: '&8&l༺ %tiered%Lvl %mob-lvl%&8 | &f%displayname%&8 | &f%entity-health-rounded% %tiered%%heart_symbol% &r%health-indicator% &8&l༻'
      health-indicator:
        indicator: '█'
        indicator-half: '▌'
        colored-tiers:
          tier-1: '&#22E76B' #Green
          tier-2: '&#528CFF' #Blue
          tier-3: '&#FFCD56' #Yellow
          tier-4: '&#FE803C' #Orange
          tier-5: '&#F2003D' #Red
          tier-6: '&#B447FF' #Purple
          default: '&#FFFFFF' #White
        merge: true

  nametag_using_numbers:
#   This controls the nametag, where the health is displayed using %entity-health-rounded%
    name: 'Nametag - Health Numerical'
    apply-settings:
      nametag: '&8&l༺ %tiered%Lvl %mob-lvl%&8 | &f%displayname%&8 | &f%entity-health-rounded%&8/&f%entity-max-health-rounded% %tiered%%heart_symbol% &8&l༻'


# +-------------------------------------------------------------------------------------------LM3
# +                                                                                          +LM3
# +   L O W E S T   P R I O R I T Y                                                          +LM3
# +   Section 03 - Default Rules                                                             +LM3
# +                                                                                          +LM3
# +   This section sets the minimum required information for LevelledMobs to function!       +LM3
# +   Much of this is managed by the PRESETS system, however a few configuration lines are   +LM3
# +   listed individually as well. If you need help understanding the DEFAULT RULES,         +LM3
# +   read the official LevelledMobs Wiki!                                                   +LM3
# +   https://github.com/lokka30/LevelledMobs/wiki/Documentation---rules.yml#default-rule    +LM3
# +                                                                                          +LM3
# +-------------------------------------------------------------------------------------------LM3
default-rule:
  use-preset:
    - allowed_worlds
    - nametag_using_numbers
#    - nametag_using_indicator
#    - basic_challenge
#    - average_challenge
    - advanced_challenge
#    - extreme_challenge
    - apply_LevellingVariance
#    - weighted_random_basic
#    - weighted_random_average
    - weighted_random_advanced
#    - weighted_random_extreme
#    - spawn_Levelling
#    - blended_Levelling
#    - ycoord_Levelling
#    - random_Levelling
    - player_Levelling

  conditions:
    allowed-spawn-reasons:
      excluded-list: ['SPAWNER']

    level-plugins:
      DANGEROUS_CAVES: false
      ECO_BOSSES: false
      MYTHIC_MOBS: false
      ELITE_MOBS: false
      ELITE_MOBS_NPCS: false
      ELITE_MOBS_SUPER_MOBS: false
      INFERNAL_MOBS: false
      CITIZENS: false
      SHOPKEEPERS: false
      SIMPLE_PETS: false
      ELITE_BOSSES: false
      BLOOD_NIGHT: false

#    apply-above-y: 64
#    apply-below-y: 59
#    min-distance-from-spawn: 1000
#    max-distance-from-spawn: 5000

    mob-customname-status: EITHER
    mob-tamed-status: EITHER

  apply-settings:
    sunlight-intensity: 5

    entity-name-override:
#      HUSK: ['Husk', 'Desert Zombie', 'Lost Soul', 'Dessicated Corpse']
#      SKELETON: ['Bones', 'Billy Bones', 'Verta Brae']
#      PILLAGER: ['Raider', 'Barbarian']

    creature-death-nametag: '%tiered%Lvl %mob-lvl%&8 | &f%displayname%'
    nametag-placeholder-levelled: ''
    nametag-placeholder-unlevelled: ''
    nametag-visible-time: 1000
    nametag-visibility-method: ['TARGETED', 'ATTACKED', 'TRACKING']

    baby-mobs-inherit-adult-setting: true
    level-inheritance: true
    passenger-match-level: false

    use-custom-item-drops-for-mobs: true

    maximum-death-in-chunk-threshold: 0
    max-adjacent-chunks: 3
    chunk-max-cooldown-seconds: 300
    disable-vanilla-drops-on-chunk-max: false

    spawner-particles: 'SOUL'
    spawner-particles-count: 10

# +-------------------------------------------------------------------------------------------LM3
# +                                                                                          +LM3
# +   H I G H E S T   P R I O R I T Y                                                        +LM3
# +   Section 04 - Custom Rules                                                              +LM3
# +                                                                                          +LM3
# +   This section applies CUSTOM RULES, or exceptions, to the DEFAULT RULE. These rules     +LM3
# +   modify the DEFAULT RULE to achieve your desired effect. Establish a CONDITION to       +LM3
# +   check for, then set either a STRATEGY or APPLY-SETTINGS when the CONDITION is met.     +LM3
# +   If you need help understanding CUSTOM RULES, read the official LevelledMobs Wiki!      +LM3
# +   https://github.com/lokka30/LevelledMobs/wiki/Documentation---rules.yml#custom-rules    +LM3
# +                                                                                          +LM3
# +-------------------------------------------------------------------------------------------LM3
custom-rules:
  - enabled: true
    name: 'CR - NoLevel All Passive + EntityTypes'
    use-preset: allowed_worlds
    conditions:
      entities:
        allowed-groups: ['all_passive_mobs']
        allowed-list: ['BABY_', 'ENDER_DRAGON', 'WITHER', 'VILLAGER', 'ZOMBIE_VILLAGER', 'WANDERING_TRADER', 'PHANTOM', 'BAT', 'RAVAGER']
    apply-settings:
      maxLevel: 0

  - enabled: true
    name: 'CR - Custom Nether Levelling'
    use-preset: apply_LevellingVariance
    conditions:
      worlds:
        allowed-list: ['world_nether']
    strategies:
      y-coordinate:
        start: 100
        end: 40
        period: 0

  - enabled: true
    name: 'CR - Custom Entity Attributes'
    use-preset: allowed_worlds
    apply-settings:
      multipliers:
        custom-mob-level:
          ENDERMAN:
            max-health: 0.0
            movement-speed: 0.0
          SILVERFISH:
            max-health: 0.0
            movement-speed: 0.0
          CREEPER:
            movement-speed: 0.025
          WITHER_SKELETON:
            max-health: 1.0

  - enabled: true
    name: 'CR - Custom Zombie Piglin Levelling'
    conditions:
      worlds:
        allowed-list: ['world_nether']
      entities:
        allowed-list: ['ZOMBIFIED_PIGLIN']
    strategies:
      random: true
    apply-settings:
      minLevel: 1
      maxLevel: 5
      multipliers:
        custom-mob-level:
          ZOMBIFIED_PIGLIN:
            max-health: 1.0
            movement-speed: 0.25
            attack-damage: 0.5
            ranged-attack-damage: 0.0
            item-drop: 0.5
            xp-drop: 1.0
      tiered-coloring:
        1-5: '&#22E76B' #Green


# +-------------------------------------------------------------------------------------------LM3
# +                                                                                          +LM3
# +   Section 05 - Advanced Message Settings                                                 +LM3
# +   DO NOT EDIT BEYOND HERE WITHOUT DEVELOPER APPROVAL                                     +LM3
# +                                                                                          +LM3
# +-------------------------------------------------------------------------------------------LM3
file-version: 3`

can someone please tell me what I'm doing wrong

**Comment by Eris7090** [comment]
Now nothing has levels

**Comment by stumper66** [comment]
Closing this issue as we resolved your issue in discord.
If you still need help you can open a ticket there.
