### ISSUE TITLE
Any time I add more tiers for player leveling then levels stops working completly

### ISSUE THREAD

**Issue by Eris7090** [lokka30/LevelledMobs#385]
**Describe the bug**
add tiers for player leveling and it break

**Steps to Reproduce**
1. add tier
2. progress

**Expected behavior**
to have more tiers so scaling is so hard on my server
**Screenshots**

**Server software**
purpur

**Server version**
Minecraft 1.18.2

**LevelledMobs version**
Please copy and paste the output of `/version LevelledMobs`.

**Config files, if applicable**
https://paste.gg/p/anonymous/70b2e37806944db6b483f38e64daafd0

**Additional context**

**Comment by lokka30** [comment]
Hi @Eris7090, did you discuss this on our Discord? Additionally, make sure to fill out the 'LevelledMobs version' heading with the output of `/version LevelledMobs`.

**Comment by stumper66** [comment]
This was solved days ago. He didn't have the correct spacing in rules.yml
