### ISSUE TITLE
Disable plugin on some worlds

### ISSUE THREAD

**Issue by FortiethSwing61** [lokka30/LevelledMobs#391]
Does this feature already exist? If Yes, I can't find the  'disabled worlds' part

**Comment by lokka30** [comment]
See https://github.com/lokka30/LevelledMobs/blob/master/src/main/resources/rules.yml#L190

**Comment by FortiethSwing61** [comment]
I did that but I can still spawn levelled mobs

**Comment by lokka30** [comment]
For further support, feel free to join our Discord and use the levelledmobs chat. We only use the issue tracker for bugs and ideas now :)
