### ISSUE TITLE
All monsters are level 25 no matter the location

### ISSUE THREAD

**Issue by Tortilladog** [lokka30/LevelledMobs#396]
I went into the rules.yml file in the plugin and un-hashed  - blended_Levelling in the use-preset list. When I joined my server, all monsters were level 25 no matter their height or distance from spawn. Are there extra steps I was not aware of, or is this a bug?

My Config Files:

[server101389 - 8 Jul 2022 16_52_18.zip](https://github.com/lokka30/LevelledMobs/files/9074969/server101389.-.8.Jul.2022.16_52_18.zip)

**Comment by stumper66** [comment]
for blended levelling you also need spawn distance levelling, so uncomment that.
also you should comment out - average_challenge

please join our discord for real-time support

**Comment by lokka30** [comment]
closed: see above :)
