### ISSUE TITLE
Multiple Drop Tables

### ISSUE THREAD

**Issue by Islati** [lokka30/LevelledMobs#397]
**Describe the solution you'd like**
I'd like to be able to define a drop table for the customdrops.yml file, and allow mobs to have multiple potential drop tables used to build their loot table, each with a chance of being polled aswell.

**Comment by UltimaOath** [comment]
You can do this already by utilizing the Custom Rule system and
use-droptable-id

**Comment by UltimaOath** [comment]
Change any `conditions:` to reflect any limits from entity to level to world, etc.
