### ISSUE TITLE
[Feature Request] Releveling mobs based on lowest level player within radius

### ISSUE THREAD

**Issue by Folas1337** [lokka30/LevelledMobs#404]
**Is your feature request related to a problem? Please describe.**
Barely a problem, more of an inconvenience that sometimes low level players are attacked by high level mobs as they aren't releveling fast enough.

**Describe the solution you'd like**
I'd like to have a config option which allows me to change the "async-task-max-blocks-from-player" behavior so that it selects the lowest level player instead of the closest player to the mob.
Basically when a mob is attempted to be relevelled it will check if a low level player is within that radius and then set the mob to the level of the lowest player.

An example to clarify: A player that spawns Lv 100 mobs (well call them Alice) and one with Lv 1 mobs (Bob) meet each other. Alice is fighting a mob and thus the mob is set to level 100 but then Bob approaches and Alice for example dies. In the current setup the mob would quickly turn around and probably one hit Bob, not exactly pleasant for Bob.
With this new feature Bob would come close to Alice and the mob would be changed to level 1 rather quickly. _In this scenario I'd probably pick a lower than 100 block radius but I guess it gets the idea across._

**Describe alternatives you've considered**
None, there are none according to @stumper66 

**Additional context**
Discord discussion started here: <https://discord.com/channels/752310043214479462/760051505067458590/1007754819492139008>

**Comment by UltimaOath** [comment]
#322 Features this request; closing this as a duplicate.
