### ISSUE TITLE
Incorrect passive mob group criteria

### ISSUE THREAD

**Issue by Brikster** [lokka30/LevelledMobs#407]
Not all the entities, that implements `org.bukkit.entity.Animals`, are passive mobs. For example, [Hoglin](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Hoglin.html) extends `org.bukkit.entity.Animals`, but they're hostile mobs. [Check out here.](https://github.com/lokka30/LevelledMobs/blob/eeaf7d5fdef4e40421d74142366b1f70828e4378/src/main/java/me/lokka30/levelledmobs/misc/LivingEntityWrapper.java#L930)

**Comment by UltimaOath** [comment]
[https://github.com/lokka30/LevelledMobs/blob/09c96de99b13b3fef80f1917d1873857c7d1b88b/src/main/java/me/lokka30/levelledmobs/compatibility/Compat1_16.java](https://github.com/lokka30/LevelledMobs/blob/09c96de99b13b3fef80f1917d1873857c7d1b88b/src/main/java/me/lokka30/levelledmobs/compatibility/Compat1_16.java)  
  
[https://github.com/lokka30/LevelledMobs/blob/09c96de99b13b3fef80f1917d1873857c7d1b88b/src/main/java/me/lokka30/levelledmobs/compatibility/Compat1_17.java](https://github.com/lokka30/LevelledMobs/blob/09c96de99b13b3fef80f1917d1873857c7d1b88b/src/main/java/me/lokka30/levelledmobs/compatibility/Compat1_17.java)  
  
[https://github.com/lokka30/LevelledMobs/blob/09c96de99b13b3fef80f1917d1873857c7d1b88b/src/main/java/me/lokka30/levelledmobs/compatibility/Compat1_19.java](https://github.com/lokka30/LevelledMobs/blob/09c96de99b13b3fef80f1917d1873857c7d1b88b/src/main/java/me/lokka30/levelledmobs/compatibility/Compat1_19.java)  
  
These files make updates to the type of entities, and we do make some changes based on the entity in question if they were Neutral mobs to begin with, if it made sense to put them into the Hostile group. Let me know if this resolves things for you.

**Comment by lokka30** [comment]
> Not all the entities, that implements `org.bukkit.entity.Animals`, are passive mobs. For example, [Hoglin](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Hoglin.html) extends `org.bukkit.entity.Animals`, but they're hostile mobs. [Check out here.](https://github.com/lokka30/LevelledMobs/blob/eeaf7d5fdef4e40421d74142366b1f70828e4378/src/main/java/me/lokka30/levelledmobs/misc/LivingEntityWrapper.java#L930)

Thanks 😃

**Comment by lokka30** [comment]
To clear things up. The 'check out here' link makes Hoglins a passive mob, and the Compat 1.16 class makes hoglins also a hostile mob. We need to make it so the fallback passive checker ignores hoglins. .... rather actutally, we should probably not have hostile/passive entity lists for each compatible version, a list of stringified constants is better, that would remove the overlap.

**Comment by stumper66** [comment]
This is resolved with 3.7.0 b682.
