### ISSUE TITLE
levelled guardians dont increase damage

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#42]

**Comment by UltimaOath** [comment]
Potentially useful to narrow down issue; might also fix others.
https://minecraft.fandom.com/wiki/Damage#Inflicted_by_mobs
This is a list of damage inflicted by mobs, including their variations. For example, Guardian has the Laser and Spikes attack which might be handled differently than the standard attack_damage feature. The same would probably hold true for other similar attacks like the Elder Guardian.

**Comment by lokka30** [comment]
See b361

**Comment by lokka30** [comment]
Tested
