### ISSUE TITLE
add for plugin advencedspawner

### ISSUE THREAD

**Issue by arkange83560** [lokka30/LevelledMobs#420]
Hello I propose if possible to add to the plugin, the AdvancedSpawners plugin a plugin of creation of mobs the only options that it misses has this plugin the options of lvl and other option that levellemobs proposes, I do not know if there was a request for that! I await your answer thank you;)

**Comment by lokka30** [comment]
Hi, see [here](https://github.com/lokka30/LevelledMobs/wiki/Frequently-Asked-Questions#how-do-i-make-mobs-from-monster-spawners-levelled).
