### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by FadeKivi** [lokka30/LevelledMobs#46]
[14:39:02] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to LevelledMobs v1.26
java.lang.NullPointerException: null
	at io.github.lokka30.levelledmobs.listeners.LCreatureSpawn.onMobSpawn(LCreatureSpawn.java:47) ~[?:?]

**Comment by Eyrian2010** [comment]
We need the whole error log to be able to pinpoint the problem, can you provide it please?

**Comment by lokka30** [comment]
This issue will be closed within 7 days of opening the issue if not responded to by @FadeKivi. I haven't been provided enough information to track this down. I can't find the member on Spigot by their GitHub tag.

### Make sure:
- You are running a SpigotMC or PaperMC server, version 1.15, 1.15.1, or 1.15.2. I don't support other versions.

### Please:
- Copy your settings.yml file, paste it and save it into hastebin.com. put the link in a reply.
- Copy the whole exception printed in console and, paste it and save it in hastebin.com. put the link in a reply.

### If we can't figure out what's wrong with those two links, I'll also need:
- Your list of plugins (can DM me if required). Will only be shared to people who are working on the issue.
- If you want, list any plugins which might be conflicting with the plugin's spawning.

**Comment by lokka30** [comment]
Issue closed due to a lack of reply by the poster.
