### ISSUE TITLE
higher level creeper = higher level blast damage

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#47]
higher level creeper = their explosions do more damage to ENTITIES.
a config boolean states that higher level creepers = their explosions do more damage to BLOCKS too.

**Comment by lokka30** [comment]
'creeper explosion multiplier'

**Comment by stumper66** [comment]
This has been implemented in version 1.4.  A new value in settings.yml has been added "creeper-max-damage-radius".  Configuring this with a value higher than 3 will scale up the damage radius for leveled up creepers.
If you want to have creepers become an atomic bomb put a value of 100 in there!
