### ISSUE TITLE
per-entity level cap

### ISSUE THREAD

**Issue by Achent007** [lokka30/LevelledMobs#50]
Add the possibility to lock a mob to an specific level.
Ex : 
mob-level:
  - Enderman: 5
  - Zombie: 10

In this exemple, the enderman can't be level 10 but the zombie can

**Comment by lokka30** [comment]
Great idea, thanks! Once I learn more about working with files, I'll work on this :)

**Comment by lokka30** [comment]
Done, needs testing.

**Comment by lokka30** [comment]
Done, tested, works perfectly. @Achent007 it will be released in the next update :)
