### ISSUE TITLE
mobs dont spawn with distance from spawn levelling and max-level higher than 10

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#51]
The plugin doesn't spawn mobs when the maxlevel is higher than 10 and distance from spawn levelling is on. there are no errors in console so there is no further information about the bug.
Haven't tested this myself but reported by spigotmc user **SteeniZz** in the plugin's discussion tab.

**Comment by Eyrian2010** [comment]
I'll check the code on monday, if no update is pushed until then.

**Comment by Eyrian2010** [comment]
Code looks ok. Need to test if a commit broke the method, but I can remember testing higher levels before pushing the commit. Next update in ~8h.

**Comment by lokka30** [comment]
Unfortunately I am further cut off on free time now :( I won't be able to work on any updates.

**Comment by lokka30** [comment]
As said above, the code looks completely fine. I have no idea why this is happening.

**Comment by Eyrian2010** [comment]
Did not find any errors on the newset version of the plugin + latest spigot build. Mobs spawn, and arae levelled correctly. Maybe another plugin prevents spawning. Does the log show any errors?

**Comment by lokka30** [comment]
As this was reported in the discussions page, [I have forwarded your message](https://www.spigotmc.org/threads/%E2%AD%90levelledmobs%E2%AD%90-a-simple-drag-n-drop-solution-for-mob-difficulty.412953/page-3#post-3724522) over there. 👍

**Comment by HalfOfMoon** [comment]
* spawn-distance-levelling does not work if I increase the max-level to go above 10.

As far as I know there are no other plugins that prevents levelledmobs from working. I haven't had the time to run the plugin by itself so I can't tell for sure, but none of the plugins installed doesn't manipulate how the mobs are treated.

No errors in console. Only the regular "plugin enabled" message.
`21.03 18:48:15 [Server] INFO [LevelledMobs] Enabling LevelledMobs v1.27
21.03 18:48:15 [Server] INFO [LevelledMobs] [1/6] Checking compatibility...
21.03 18:48:15 [Server] INFO [LevelledMobs] Server is running supported version git-Paper-143 (MC: 1.15.2).
21.03 18:48:15 [Server] INFO [LevelledMobs] [2/6] Loading files...
21.03 18:48:15 [Server] INFO [LevelledMobs] [3/6] Registering events...
21.03 18:48:15 [Server] INFO [LevelledMobs] [4/6] Registering commands...
21.03 18:48:15 [Server] INFO [LevelledMobs] [5/6] Hooking to other plugins...
21.03 18:48:15 [Server] INFO [LevelledMobs] [6/6] Starting metrics...
21.03 18:48:15 [Server] INFO [LevelledMobs] Loaded successfuly. Thank you for choosing LevelledMobs!
21.03 18:48:15 [Server] INFO [LevelledMobs] [Update Checker] Starting version comparison...`

Running the latest version (1.27) on the latest paper build.
`This server is running Paper version git-Paper-143 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`

**Comment by Eyrian2010** [comment]
hmmm... running paper, need to check that. tested on spigot 1.15.2 will come back after testing

**Comment by lokka30** [comment]
Received another report that the same issue is happening. However, they say that they can go up to level 15 before it breaks.

**Comment by lokka30** [comment]
The 'variance' feature seems to be the one breaking the level generation.

**Comment by lokka30** [comment]
Should be resolved in 1.30.0-RELEASE
