### ISSUE TITLE
Shulker don't level-up despite being aggressive mobs.

### ISSUE THREAD

**Issue by Eyrian2010** [lokka30/LevelledMobs#52]

**Comment by lokka30** [comment]
if shulker entity isn't an instance of a hostile monster, that's probably it

**Comment by lokka30** [comment]
Thought of a solution.
Once issue #44 is added,
'SHULKER' can be added to the blacklist-override by default.
This will force shulkers to be levelled.

I explored the Shulker class and for some reason it isn't instanceof monster

**Comment by lokka30** [comment]
Fixed in upcoming release
