### ISSUE TITLE
Custom summon command for specific levels

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#58]
`/levelledmobs summon <EntityType> <level>`
* Summons at your location
* Players only

`/levelledmobs summon <EntityType> <level> <x> <y> <z>`
* Summons to the location
* Can be ran by console

`/levelledmobs summon <EntityType> <level> <player>`
* Summons to a player
* Can be ran by console

**Comment by lokka30** [comment]
Command added. Functionality not added yet though.

**Comment by stumper66** [comment]
This has been implemented in 1.40 with the following syntax:
/lvlmobs summon <amount> <entity> <level> here
/lvlmobs summon <amount> <entity> <level> atPlayer <playername>
/lvlmobs summon <amount> <entity> <level> atLocation <x> <y> <z>

**Comment by lokka30** [comment]
> This has been implemented in 1.40 with the following syntax:
> /lvlmobs summon <amount> <entity> <level> here
> /lvlmobs summon <amount> <entity> <level> atPlayer <playername>
> /lvlmobs summon <amount> <entity> <level> atLocation <x> <y> <z>

Are the commands fully functional?

**Comment by stumper66** [comment]
You betcha.   100% complete

**Comment by lokka30** [comment]
Tested, all working :)
