### ISSUE TITLE
Levelling mode: 'mcmmo'

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#60]
When a mob enters combat, set their levels to the player's mcmmo level

**Comment by stumper66** [comment]
I'm not sure of the feasibility of this one.  Basically a process would need to constantly check how close all players are to any mobs then adjust their stats according to the player's level.  Sounds like it would be a huge resource hog for the server.
Unless there is a better way to do this I don't think it is feasible at all.

**Comment by lokka30** [comment]
> I'm not sure of the feasibility of this one. Basically a process would need to constantly check how close all players are to any mobs then adjust their stats according to the player's level. Sounds like it would be a huge resource hog for the server.
> Unless there is a better way to do this I don't think it is feasible at all.

Absolutely - the huge loss in performance is exactly why 'mcmmo' or 'player' levelling modes have not been added. I will close this as some server owners will ignore the consequences if it were added.
