### ISSUE TITLE
All mobs are Level 0 in latest snapshot

### ISSUE THREAD

**Issue by magcynic** [lokka30/LevelledMobs#7]
I had to revert to the 1.8 snapshot to get mobs to spawn at random levels.  I do not see any config file or command in-game to change how often higher level mobs spawn, either.

**Comment by lokka30** [comment]
Currently investigating on Discord. Unlikely to be an issue with the plugin, rather a simple user error.
Status- awaiting response.

**Comment by lokka30** [comment]
Confirmed that settings file was outdated.
