### ISSUE TITLE
getDefaultValue() != getBaseValue()

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#77]

**Comment by lokka30** [comment]
* Settings file confirmed as being read.
* Need to check if there is an excess addition to the movement speed when the mob attribute is being applied.

**Comment by lokka30** [comment]
After 1.33.3 was done, new debug information was added.

The debug information has shown that the multipliers stated that:
- the multipliers in the settings file are being read properly.
- setting the movement multiplier to `0` will keep the movement speed default for all levelled mobs.
- the default movement speed assigned to mobs might be too high.

**Conclusions from testing**
- Temporarily use 'getBaseValue' instead of 'getDefaultValue' for the movement speed attribute. See if the `base value` is lower than the `default value`. This will conclude with any of these options:
  - the normal `base value` is lower than the `default value`. spigot bug?
  - the normal `base value` is the same as the `default value`. disable the movement speed attribute change and see if levelledmobs is causing the drastic movement speed.
  - the normal `base value` is higher than the `default value`. spigot bug?

**Comment by lokka30** [comment]
Status - temporarily made it use `base value` instead of `default value`. need to get results now.

**Comment by lokka30** [comment]
Testing has found that the `default value` is around 3x higher than the `base value`. Will ask the Spigot community about this one.

**Comment by lokka30** [comment]
Thread posted [here](https://www.spigotmc.org/threads/attributes-getdefaultvalue-getbasevalue.440635/).

**Comment by lokka30** [comment]
Will fix #57

**Comment by stumper66** [comment]
I tried changing it out for getDefaultValue() but all the mobs were moving like Speedy Gonzales.  It's possible it would work with tweaking of all the multiplier values but I decided it wasn't worth all the effort.  It would basically force people to start over with their multiplier values when they upgraded.

**Comment by lokka30** [comment]
> I tried changing it out for getDefaultValue() but all the mobs were moving like Speedy Gonzales. It's possible it would work with tweaking of all the multiplier values but I decided it wasn't worth all the effort. It would basically force people to start over with their multiplier values when they upgraded.

I will add an 'attributes.yml' file with all of the default entity attributes. LM will read this file.
I am unsure why the `getDefaultValue()` method is returning very obscure values - speedy gonzales as you wrote - I don't believe Spigot will do anything about it either within a lifetime, so it seems the `attributes.yml` thing will have to happen.

**Comment by lokka30** [comment]
To add on to my reply, I will add a hidden command only accessible to console which will spawn in every entity and write all of their default attributes to the file. Of course, I will ship out a pre-generated file by default so server owners won't need to worry about it.

**Comment by lokka30** [comment]
Issue merged. See #116
