### ISSUE TITLE
Refactor levelling system -- make a listener ignore a certain mob

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#81]
### About the issue:
* Currently, the functions for applying levels to mobs are completely situated in the * CreatureSpawnListener.
* I have received two requests so far of features which require spawning of entities of specific levels, and I can't do this as the mob's level will be applied as a random one as soon as they spawn in.

### Why does this need to be done?
* better code, of course.
* regular mobs spawning normally get the random level (as currently is in place)
* #58  and #63  can allow spawning of certain level mobs

### Current problem with the issue:
* I'm not sure how to make an entity spawn and tell the CreatureSpawnListener to ignore it. Once this has been overcome, I can easily transfer the level application system from the listener to LevelManager#applyLevel, for example.

**Comment by ShayPunter** [comment]
For this you can place a check for a mob, then have a list of entities in the configuration file of what you don't want to be levelled, if the mob matches the one in the description file, it just returns and doesn't run it through the levelling process

**Comment by lokka30** [comment]
> 
> 
> For this you can place a check for a mob, then have a list of entities in the configuration file of what you don't want to be levelled, if the mob matches the one in the description file, it just returns and doesn't run it through the levelling process

I apologise, I didn't explain it correctly. I'll edit the original post now so it makes more sense what I was aiming to achieve ;)

**Comment by stumper66** [comment]
I will add this to the next version

**Comment by lokka30** [comment]
> I will add this to the next version

You've already added this in with your summon command. :)
