### ISSUE TITLE
Mob stop making any sound

### ISSUE THREAD

**Issue by Phaired** [lokka30/LevelledMobs#83]
sometimes the monster are stop making any sound and LevelledMobs is the only plugin I use who modify the monster so I think it can be the cause. here's my plugin list 
<img width="1526" alt="Capture d’écran 2020-05-30 à 21 14 22" src="https://user-images.githubusercontent.com/65019388/83338366-04709c00-a2c4-11ea-86b9-67ae6fa59f9c.png">

**Comment by lokka30** [comment]
100% not an issue with my plugin. I promise you. :)

**Comment by lokka30** [comment]
You also have *heaps* of plugins in there which tinker with entities. I'd point you to look at plugins which use packets. Uninstall plugins one by one until you can hear mob sounds. If it's none of your plugins then it is your client.
