### ISSUE TITLE
Commands executed by console when a levelled mob dies. Per-level commands too.

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#84]
Suggested by Burgil

**Comment by stumper66** [comment]
I am wondering if this is a security risk doing this?  Basically commands in the config would be executed by the console if I understand it right.

**Comment by lokka30** [comment]
> I am wondering if this is a security risk doing this? Basically commands in the config would be executed by the console if I understand it right.

Absolutely. In addition, mob grinders and such could cause a lot of commands to be executed in a short period of time. I believe this issue should too be closed although I will leave it open in case anyone wishes to comment as it is not difficult to implement.

Regarding a security risk - anyone that even has access to the plugin's configuration file should be dearly trusted by a server owner. I don't see any security risk at all. A user which has access to the files can also modify permission plugin configuration files, the `ops.txt` file, so on.

**Comment by lokka30** [comment]
Example config idea:
```
console-commands-on-lvl-mob-death:
 natural-caused: # if a player didn't kill it
    "1, 2, 3, 4, 5":
     - 'airdrop start %world% %location%'
    "6, 7, 8, 9, 10":
     - 'say A mob was killed at %location% in world %world%'
    "6, 7, 10": # levels can be assigned to multiple command groups
     - 'say A level %level% mob was killed naturally.'
 player-caused: # if the player was the killer
    "1, 3, 5, 7, 9":
     - 'say Well done %player%.'
     - 'xp give %player% 2"
   "2, 4, 6, 8, 10":
     - 'give %player% diamond %level%' # %level% placeholder = level of the mob killed
```

**Comment by lokka30** [comment]
This was added by #208 , need to check if this issue is still meant to be open.
