### ISSUE TITLE
WorldGuard flag which toggles if mobs get levelled in a region.

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#85]
Requested by BecauseNyx.

**Comment by stumper66** [comment]
Am I missing something or is this already implemented?  In version 1.34 there are 3 flags,  'CustomLevelFlag', 'MinLevelFlag', 'MaxLevelFlag'.
by changing CustomLevelFlag to allow or deny you can toggle if mobs will get leveled in that region.

**Comment by lokka30** [comment]
> Am I missing something or is this already implemented? In version 1.34 there are 3 flags, 'CustomLevelFlag', 'MinLevelFlag', 'MaxLevelFlag'.
> by changing CustomLevelFlag to allow or deny you can toggle if mobs will get leveled in that region.

Ah, it seems this would already be implemented then. Thank you.
