### ISSUE TITLE
Setting to only spawn hostile levelled mobs

### ISSUE THREAD

**Issue by ShayPunter** [lokka30/LevelledMobs#9]
Suggestion: Ability to spawn only hostile mobs with levels

**Comment by ShayPunter** [comment]
Not too sure if this is the case, I have seen villagers with levels on the server, just checking through the code now and it seems to be already implemented

**Comment by lokka30** [comment]
Unless the new feature isn't working as expected, individual entities can be filtered out of the levelling system in the settings file.
Would you like me to add a boolean in settings.yml to ignore passive mobs?

**Comment by lokka30** [comment]
Added a boolean in settings to ignore passive mobs in upcoming release.
