### ISSUE TITLE
superscript format or text for the level

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#94]
e.g. `Zombie ²`.
Suggested by https://www.spigotmc.org/members/bvssy.448126/

**Comment by stumper66** [comment]
I don't think this is possible as I haven't seen enumerations for superscript in the bukkit API.
On my other plugin FindPlayer, I enumerated all available text manipulation values (https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/ChatColor.html) and made placeholders for them.  It looked like this:

		v.put("{AQUA}", ChatColor.AQUA);
		v.put("{BLACK}", ChatColor.BLACK);
		v.put("{BLUE}", ChatColor.BLUE);
		v.put("{BOLD}", ChatColor.BOLD);
		v.put("{DARK_AQUA}", ChatColor.DARK_AQUA);
		v.put("{DARK_BLUE}", ChatColor.DARK_BLUE);
		v.put("{DARK_GRAY}", ChatColor.DARK_GRAY);
		v.put("{DARK_GREEN}", ChatColor.DARK_GREEN);
		v.put("{DARK_PURPLE}", ChatColor.DARK_PURPLE);
		v.put("{DARK_RED}", ChatColor.DARK_RED);
		v.put("{GOLD}", ChatColor.GOLD);
		v.put("{GRAY}", ChatColor.GRAY);
		v.put("{GREEN}", ChatColor.GREEN);
		v.put("{ITALIC}", ChatColor.ITALIC);
		v.put("{LIGHT_PURPLE}", ChatColor.LIGHT_PURPLE);
		v.put("{MAGIC}", ChatColor.MAGIC);
		v.put("{RED}", ChatColor.RED);
		v.put("{RESET}", ChatColor.RESET);
		v.put("{STRIKETHROUGH}", ChatColor.STRIKETHROUGH);
		v.put("{UNDERLINE}", ChatColor.UNDERLINE);
		v.put("{WHITE}", ChatColor.WHITE);
		v.put("{YELLOW}", ChatColor.YELLOW);

**Comment by lokka30** [comment]
> I don't think this is possible as I haven't seen enumerations for superscript in the bukkit API.
> On my other plugin FindPlayer, I enumerated all available text manipulation values (https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/ChatColor.html) and made placeholders for them. It looked like this:
> 
> ```
> 	v.put("{AQUA}", ChatColor.AQUA);
> 	v.put("{BLACK}", ChatColor.BLACK);
> 	v.put("{BLUE}", ChatColor.BLUE);
> 	v.put("{BOLD}", ChatColor.BOLD);
> 	v.put("{DARK_AQUA}", ChatColor.DARK_AQUA);
> 	v.put("{DARK_BLUE}", ChatColor.DARK_BLUE);
> 	v.put("{DARK_GRAY}", ChatColor.DARK_GRAY);
> 	v.put("{DARK_GREEN}", ChatColor.DARK_GREEN);
> 	v.put("{DARK_PURPLE}", ChatColor.DARK_PURPLE);
> 	v.put("{DARK_RED}", ChatColor.DARK_RED);
> 	v.put("{GOLD}", ChatColor.GOLD);
> 	v.put("{GRAY}", ChatColor.GRAY);
> 	v.put("{GREEN}", ChatColor.GREEN);
> 	v.put("{ITALIC}", ChatColor.ITALIC);
> 	v.put("{LIGHT_PURPLE}", ChatColor.LIGHT_PURPLE);
> 	v.put("{MAGIC}", ChatColor.MAGIC);
> 	v.put("{RED}", ChatColor.RED);
> 	v.put("{RESET}", ChatColor.RESET);
> 	v.put("{STRIKETHROUGH}", ChatColor.STRIKETHROUGH);
> 	v.put("{UNDERLINE}", ChatColor.UNDERLINE);
> 	v.put("{WHITE}", ChatColor.WHITE);
> 	v.put("{YELLOW}", ChatColor.YELLOW);
> ```

This would be the way to go to implement this feature.

**Comment by lokka30** [comment]
This request seems like it would have a very low utilisation, so I don't see a net benefit of adding it.

**Comment by lokka30** [comment]
Closing it due to the above. Niche issue
