### ISSUE TITLE
Can't get some mobs to level (tried with Ghasts and Magma Cubes so far)

### ISSUE THREAD

**Issue by RWoof** [lokka30/LevelledMobs#96]
Running Paper 1.16.1 build 136, in the nether, magma cubes and ghasts don't seem to level, even if they're in the blacklist override or min/max mob level.

I tried the names MAGMA_CUBE, MAGMA CUBE, MAGMACUBE, and the same in lower case and none seemed to work, there's a good chance I've just got the names wrong. Is there a list somewhere?

They do level with passive mobs turned on, but I don't want all passives to level. Is there a way around this?

**Comment by lokka30** [comment]
Hi @RWoof, thanks for reporting this issue. From a code point of view, the entities that you stated likely are not 'instance of' `Monster`, and that's what LevelledMobs uses to classify entities as 'passive' or 'hostile',
I'll take a look at this next time I work on LevelledMobs. Thanks again, have a great day :)

**Comment by RWoof** [comment]
Thanks and hope you can get it fixed for everyone 😊

**Comment by stumper66** [comment]
This has been fixed in 1.4.0
