### ISSUE TITLE
level dependent on Y level option

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#99]
suggested by Oathkeeper

**Comment by stumper66** [comment]
I'm trying to think of the best way this would be configured.
Would it be two settings, starting level Y, then another setting on how far away from the starting Y it would take for each level to increase?
For example starting Y is 20.  Distance value is 5 so mobs on y25 get level 23, y30 gets level 3 and so on.  Not sure if that's the best way.

**Comment by lokka30** [comment]
> I'm trying to think of the best way this would be configured.
> Would it be two settings, starting level Y, then another setting on how far away from the starting Y it would take for each level to increase?
> For example starting Y is 20. Distance value is 5 so mobs on y25 get level 2, y30 gets level 3 and so on. Not sure if that's the best way.

It would definitely be a very similar system to 'distance from spawn levelling'.
* Starting Y
* Ending Y
* Y-period (how many blocks per level)
* Variance (the level is +/- by a random number with a configurable max and min variance)

**Comment by stumper66** [comment]
Implemented in version 1.35
